const r=require('express').Router();const c=require('./controller');const permit=require('../../middleware/permissions');const P=require('../../constants/permissions');
const wrap=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);
r.get('/options',permit(P.VIEW_ACADEMICS),wrap(c.options));
r.put('/settings',permit(P.MANAGE_ACADEMICS),wrap(c.saveSettings));
r.get('/schedule-profiles',permit(P.VIEW_ACADEMICS),wrap(c.scheduleProfiles));
r.post('/schedule-profiles',permit(P.MANAGE_ACADEMICS),wrap(c.saveScheduleProfile));
r.delete('/schedule-profiles/:id',permit(P.MANAGE_ACADEMICS),wrap(c.deleteScheduleProfile));
r.get('/schedule-resolve',permit(P.VIEW_ACADEMICS),wrap(c.resolveSchedule));

r.get('/constraints',permit(P.VIEW_ACADEMICS),wrap(c.constraints));
r.get('/class-constraints',permit(P.VIEW_ACADEMICS),wrap(c.classConstraints));
r.post('/class-constraints',permit(P.MANAGE_ACADEMICS),wrap(c.saveClassConstraint));
r.delete('/class-constraints/:id',permit(P.MANAGE_ACADEMICS),wrap(c.deleteClassConstraint));
r.delete('/class-constraint-batches/:batchId',permit(P.MANAGE_ACADEMICS),wrap(c.deleteClassConstraintBatch));
r.get('/divisions',permit(P.VIEW_ACADEMICS),wrap(c.divisions));
r.post('/divisions',permit(P.MANAGE_ACADEMICS),wrap(c.saveDivision));
r.put('/divisions/:id',permit(P.MANAGE_ACADEMICS),wrap(c.updateDivision));
r.delete('/divisions/:id',permit(P.MANAGE_ACADEMICS),wrap(c.deleteDivision));
r.post('/constraints',permit(P.MANAGE_ACADEMICS),wrap(c.saveConstraint));
r.delete('/constraints/:id',permit(P.MANAGE_ACADEMICS),wrap(c.deleteConstraint));
r.post('/generate/preview',permit(P.MANAGE_ACADEMICS),wrap(c.generatePreview));
r.post('/generate/commit',permit(P.MANAGE_ACADEMICS),wrap(c.commitGeneration));
r.post('/generate/publish',permit(P.MANAGE_ACADEMICS),wrap(c.publishGenerated));
r.get('/whole-grid',permit(P.VIEW_ACADEMICS),wrap(c.wholeGrid));
r.get('/assignments',permit(P.VIEW_ACADEMICS),wrap(c.assignments));
r.post('/assignments',permit(P.MANAGE_ACADEMICS),wrap(c.saveAssignment));
r.post('/assignments/bulk',permit(P.MANAGE_ACADEMICS),wrap(c.saveAssignmentsBulk));
r.delete('/assignments/:id',permit(P.MANAGE_ACADEMICS),wrap(c.removeAssignment));
r.get('/rooms',permit(P.VIEW_ACADEMICS),wrap(c.rooms));
r.post('/rooms',permit(P.MANAGE_ACADEMICS),wrap(c.saveRoom));
r.get('/grid',permit(P.VIEW_ACADEMICS),wrap(c.grid));
r.post('/grid',permit(P.MANAGE_ACADEMICS),wrap(c.place));
r.delete('/grid/:id',permit(P.MANAGE_ACADEMICS),wrap(c.removeSlot));
r.get('/validate',permit(P.VIEW_ACADEMICS),wrap(c.validate));
r.get('/verify-detailed',permit(P.VIEW_ACADEMICS),wrap(c.verifyDetailed));
r.put('/grid/:id/lock',permit(P.MANAGE_ACADEMICS),wrap(c.setLessonLock));
module.exports=r;
