const ExamResult=require('../../models/ExamResult');
const ExamSchedule=require('../../models/ExamSchedule');
const TeacherAssignment=require('../../models/TeacherAssignment');
const Program=require('../../models/Program');
const Section=require('../../models/Section');
const Course=require('../../models/Course');
const Employee=require('../../models/Employee');
const Wing=require('../../models/Wing');
const College=require('../../models/College');
const sid=v=>String(v?._id||v||'');
const pct=(a,b)=>b?Number((a/b*100).toFixed(2)):0;
function stat(rows){const valid=rows.filter(x=>!['withheld','pending'].includes(x.resultStatus));const appeared=valid.filter(x=>x.resultStatus!=='absent');const pass=valid.filter(x=>x.resultStatus==='pass').length,fail=valid.filter(x=>['fail','absent'].includes(x.resultStatus)).length;const ps=appeared.map(x=>Number(x.percentage||0));return{records:valid.length,students:new Set(valid.map(x=>sid(x.studentId))).size,appeared:appeared.length,pass,fail,passRate:pct(pass,valid.length),average:ps.length?Number((ps.reduce((a,b)=>a+b,0)/ps.length).toFixed(2)):0,highest:ps.length?Math.max(...ps):0,lowest:ps.length?Math.min(...ps):0};}
function group(rows,key,label){const m=new Map();for(const r of rows){const id=key(r);if(!id)continue;if(!m.has(id))m.set(id,{id,label:label(r),rows:[]});m.get(id).rows.push(r);}return [...m.values()].map(x=>({...x,...stat(x.rows),rows:undefined})).sort((a,b)=>b.average-a.average);}
exports.analytics=async(req,res)=>{try{const cid=req.collegeId||req.user?.collegeId;const q={collegeId:cid};for(const k of ['examId','sectionId','courseId'])if(req.query[k])q[k]=req.query[k];let rows=await ExamResult.find(q).lean();let schedules=await ExamSchedule.find({collegeId:cid,_id:{$in:[...new Set(rows.map(x=>sid(x.scheduleId)))]}}).lean();const sm=new Map(schedules.map(x=>[sid(x._id),x]));if(req.query.programId)rows=rows.filter(r=>sid(sm.get(sid(r.scheduleId))?.programId)===req.query.programId);if(req.query.sessionId)rows=rows.filter(r=>sid(sm.get(sid(r.scheduleId))?.academicSessionId)===req.query.sessionId);
 const assignmentIds=[...new Set(schedules.map(x=>sid(x.teacherAssignmentId)).filter(Boolean))];const assignments=await TeacherAssignment.find({collegeId:cid,_id:{$in:assignmentIds}}).lean();const am=new Map(assignments.map(x=>[sid(x._id),x]));if(req.query.teacherId)rows=rows.filter(r=>sid(am.get(sid(sm.get(sid(r.scheduleId))?.teacherAssignmentId))?.teacherId)===req.query.teacherId);
 const pids=[...new Set(schedules.map(x=>sid(x.programId)).filter(Boolean))],secids=[...new Set(rows.map(x=>sid(x.sectionId)).filter(Boolean))],cids=[...new Set(rows.map(x=>sid(x.courseId)).filter(Boolean))],tids=[...new Set(assignments.map(x=>sid(x.teacherId)).filter(Boolean))];const [programs,sections,courses,teachers]=await Promise.all([Program.find({_id:{$in:pids}}).lean(),Section.find({_id:{$in:secids}}).lean(),Course.find({_id:{$in:cids}}).lean(),Employee.find({_id:{$in:tids}}).select('name employeeNo wingType').lean()]);const pm=new Map(programs.map(x=>[sid(x._id),x])),sem=new Map(sections.map(x=>[sid(x._id),x])),cm=new Map(courses.map(x=>[sid(x._id),x])),tm=new Map(teachers.map(x=>[sid(x._id),x]));const wingIds=[...new Set(programs.map(x=>sid(x.wingId)).filter(Boolean))];const wings=await Wing.find({_id:{$in:wingIds}}).lean();const wm=new Map(wings.map(x=>[sid(x._id),x]));
 const college=await College.findById(cid).select('name code address contactNo email website logoUrl educationalSlogan').lean();
 const scheduleOf=r=>sm.get(sid(r.scheduleId))||{}, teacherOf=r=>am.get(sid(scheduleOf(r).teacherAssignmentId))||{};
 const gradeCounts={};rows.forEach(r=>{const g=r.grade||r.resultStatus||'Unassigned';gradeCounts[g]=(gradeCounts[g]||0)+1;});
 res.json({college,summary:stat(rows),teacherWise:group(rows,r=>sid(teacherOf(r).teacherId),r=>tm.get(sid(teacherOf(r).teacherId))?.name||'Teacher'),programWise:group(rows,r=>sid(scheduleOf(r).programId),r=>pm.get(sid(scheduleOf(r).programId))?.name||'Program/Class'),classWise:group(rows,r=>sid(r.sectionId),r=>{const s=sem.get(sid(r.sectionId));return `${pm.get(sid(s?.programId))?.name||''} ${s?.name||'Section'}`.trim()}),subjectWise:group(rows,r=>sid(r.courseId),r=>cm.get(sid(r.courseId))?.name||'Subject'),wingWise:group(rows,r=>sid(pm.get(sid(scheduleOf(r).programId))?.wingId),r=>wm.get(sid(pm.get(sid(scheduleOf(r).programId))?.wingId))?.name||'Wing'),gradeDistribution:Object.entries(gradeCounts).map(([label,value])=>({label,value})),meta:{teachers,programs,sections,courses,wings}}); }catch(e){res.status(500).json({error:e.message});}};