import {useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'react-router-dom';
import api from '../../api/client';
import {useAuth} from '../../contexts/AuthContext';
import './finance.css';

const tabs=[['overview','Overview'],['income','Income'],['expenses','Expenses'],['accounts','Accounts'],['transactions','Transactions'],['reports','Reports']];
const money=value=>Number(value||0).toLocaleString(undefined,{minimumFractionDigits:0,maximumFractionDigits:2});
const fmtDate=value=>value?new Date(value).toLocaleDateString():'';
const today=()=>new Date().toISOString().slice(0,10);
const emptyForm=type=>({type,transactionDate:today(),headId:'',accountId:'',fromAccountId:'',toAccountId:'',amount:'',paymentMethod:'cash',payee:'',referenceNo:'',description:''});

function ServerPager({pagination,onPage}){
  if(!pagination?.total)return null;const start=(pagination.page-1)*pagination.limit+1,end=Math.min(pagination.page*pagination.limit,pagination.total);const pages=[];for(let p=Math.max(1,pagination.page-2);p<=Math.min(pagination.pages,pagination.page+2);p++)pages.push(p);
  return <div className="cms-pagination"><span>Showing {start}–{end} of {pagination.total}</span><div className="cms-pagination-buttons"><button type="button" disabled={pagination.page<=1} onClick={()=>onPage(pagination.page-1)}>Previous</button>{pages.map(p=><button type="button" key={p} className={p===pagination.page?'active':''} onClick={()=>onPage(p)}>{p}</button>)}<button type="button" disabled={pagination.page>=pagination.pages} onClick={()=>onPage(pagination.page+1)}>Next</button></div></div>;
}

export default function FinancePage(){
  const {user}=useAuth();
  const [searchParams,setSearchParams]=useSearchParams();
  const [tab,setTabState]=useState(searchParams.get('tab')||'overview');
  const setTab=next=>{setTabState(next);setSearchParams(prev=>{const copy=new URLSearchParams(prev);copy.set('tab',next);return copy;});};
  useEffect(()=>{const next=searchParams.get('tab')||'overview';if(next!==tab)setTabState(next);},[searchParams]);

  const [dashboard,setDashboard]=useState({});
  const [accounts,setAccounts]=useState([]);
  const [heads,setHeads]=useState([]);
  const [income,setIncome]=useState({items:[],pagination:{page:1,limit:25,total:0,pages:1}});
  const [expenses,setExpenses]=useState({items:[],pagination:{page:1,limit:25,total:0,pages:1}});
  const [transactions,setTransactions]=useState({items:[],pagination:{page:1,limit:25,total:0,pages:1}});
  const [report,setReport]=useState({income:0,expense:0,net:0,count:0,rows:[]});
  const [filters,setFilters]=useState({search:'',status:'',from:'',to:'',type:'',accountId:'',headId:'',sourceModule:''});
  const [form,setForm]=useState(emptyForm('income'));
  const [accountForm,setAccountForm]=useState({name:'',type:'cash',openingBalance:'0',openingDate:today(),bankName:'',accountNumber:'',bankBranch:'',description:''});
  const [headForm,setHeadForm]=useState({type:'income',name:'',code:'',description:''});
  const [showEntry,setShowEntry]=useState(false);
  const [showAccount,setShowAccount]=useState(false);
  const [showHead,setShowHead]=useState(false);
  const [ledger,setLedger]=useState(null);
  const [msg,setMsg]=useState('');
  const [busy,setBusy]=useState(false);

  const perms=new Set(user?.permissions||user?.effectivePermissions||[]);
  const can=p=>user?.systemRole==='platform_owner'||perms.has('*')||perms.has(p);
  const canManage=can('MANAGE_FINANCE')||can('CREATE_FINANCE_TRANSACTION')||can('MANAGE_EXPENSES');
  const canSetup=can('MANAGE_FINANCE')||can('MANAGE_FINANCE_ACCOUNTS')||can('MANAGE_FINANCE_HEADS')||can('MANAGE_EXPENSES');
  const canApprove=can('MANAGE_FINANCE')||can('APPROVE_FINANCE_TRANSACTION');
  const canPost=can('MANAGE_FINANCE')||can('POST_FINANCE_TRANSACTION');
  const canReverse=can('MANAGE_FINANCE')||can('REVERSE_FINANCE_TRANSACTION');

  async function loadBase(){
    const [d,a,h]=await Promise.all([api.get('/finance/dashboard'),api.get('/finance/accounts'),api.get('/finance/heads')]);setDashboard(d.data||{});setAccounts(a.data||[]);setHeads(h.data||[]);
  }
  async function loadList(kind,page=1){
    const params={page,limit:25,...Object.fromEntries(Object.entries(filters).filter(([,v])=>v!==''))};if(kind==='income')delete params.type;if(kind==='expenses')delete params.type;
    const url=kind==='transactions'?'/finance/transactions':`/finance/${kind}`;const r=await api.get(url,{params});const set=kind==='income'?setIncome:kind==='expenses'?setExpenses:setTransactions;set(r.data||{items:[],pagination:{page:1,limit:25,total:0,pages:1}});
  }
  async function loadReport(){const r=await api.get('/finance/reports/summary',{params:Object.fromEntries(Object.entries(filters).filter(([,v])=>v!==''))});setReport(r.data||{});}
  async function refresh(){setMsg('');try{await loadBase();if(tab==='income')await loadList('income',income.pagination?.page||1);if(tab==='expenses')await loadList('expenses',expenses.pagination?.page||1);if(tab==='transactions')await loadList('transactions',transactions.pagination?.page||1);if(tab==='reports')await loadReport();}catch(e){setMsg(e?.response?.data?.error||e.message);}}
  useEffect(()=>{loadBase().catch(e=>setMsg(e?.response?.data?.error||e.message));},[]);
  useEffect(()=>{if(tab==='income')loadList('income',1).catch(e=>setMsg(e?.response?.data?.error||e.message));if(tab==='expenses')loadList('expenses',1).catch(e=>setMsg(e?.response?.data?.error||e.message));if(tab==='transactions')loadList('transactions',1).catch(e=>setMsg(e?.response?.data?.error||e.message));if(tab==='reports')loadReport().catch(e=>setMsg(e?.response?.data?.error||e.message));},[tab]);

  const activeHeads=useMemo(()=>heads.filter(h=>h.isActive!==false),[heads]);
  function startEntry(type){setForm(emptyForm(type));setShowEntry(true);setMsg('');}
  async function saveEntry(e){e.preventDefault();setBusy(true);setMsg('');try{await api.post('/finance/transactions',{...form,amount:Number(form.amount)});setShowEntry(false);setMsg('Transaction saved as Draft.');await refresh();}catch(err){setMsg(err?.response?.data?.error||err.message);}finally{setBusy(false);}}
  async function createAccount(e){e.preventDefault();setBusy(true);setMsg('');try{await api.post('/finance/accounts',{...accountForm,openingBalance:Number(accountForm.openingBalance||0)});setShowAccount(false);setAccountForm({name:'',type:'cash',openingBalance:'0',openingDate:today(),bankName:'',accountNumber:'',bankBranch:'',description:''});setMsg('Finance account created.');await loadBase();}catch(err){setMsg(err?.response?.data?.error||err.message);}finally{setBusy(false);}}
  async function createHead(e){e.preventDefault();setBusy(true);setMsg('');try{await api.post('/finance/heads',headForm);setShowHead(false);setHeadForm({type:'income',name:'',code:'',description:''});setMsg('Finance head created.');await loadBase();}catch(err){setMsg(err?.response?.data?.error||err.message);}finally{setBusy(false);}}
  async function action(tx,action,body={}){setBusy(true);setMsg('');try{await api.post(`/finance/transactions/${tx._id}/${action}`,body);setMsg(action==='reverse'?'Transaction reversed.':`Transaction ${action}d.`);await refresh();}catch(err){setMsg(err?.response?.data?.error||err.message);}finally{setBusy(false);}}
  async function reverse(tx){const reason=window.prompt(`Reason for reversing ${tx.transactionNo}:`);if(reason?.trim())await action(tx,'reverse',{reason:reason.trim()});}
  async function openLedger(account){try{const r=await api.get(`/finance/accounts/${account._id}/ledger`);setLedger(r.data);}catch(err){setMsg(err?.response?.data?.error||err.message);}}

  const transactionTable=(data,pagerKind)=><div className="finance-table-wrap"><table className="finance-table"><thead><tr><th>Date</th><th>Transaction No.</th><th>Type / Head</th><th>Account</th><th>Reference / Description</th><th className="right">Amount</th><th>Status</th><th>Action</th></tr></thead><tbody>{(data.items||[]).map(tx=><tr key={tx._id}><td>{fmtDate(tx.transactionDate)}</td><td><strong>{tx.transactionNo}</strong><small>{tx.sourceModule&&tx.sourceModule!=='finance'?`Source: ${tx.sourceModule}`:''}</small></td><td>{tx.type.replace('_',' ')}<small>{tx.headId?.name||''}</small></td><td>{tx.accountId?.name||((tx.fromAccountId&&tx.toAccountId)?`${tx.fromAccountId.name} → ${tx.toAccountId.name}`:'—')}</td><td>{tx.referenceNo||tx.sourceReference||'—'}<small>{tx.description||tx.payee||''}</small></td><td className="right">{money(tx.amount)}</td><td><span className={`finance-status finance-status-${tx.status}`}>{tx.status.replace('_',' ')}</span></td><td><div className="finance-actions">{tx.status==='draft'&&canManage&&<button type="button" onClick={()=>action(tx,'submit')} disabled={busy}>Submit</button>}{['draft','pending_approval'].includes(tx.status)&&canApprove&&<button type="button" onClick={()=>action(tx,'approve')} disabled={busy}>Approve</button>}{tx.status==='approved'&&canPost&&<button type="button" onClick={()=>action(tx,'post')} disabled={busy}>Post</button>}{tx.status==='posted'&&canReverse&&<button type="button" className="danger" onClick={()=>reverse(tx)} disabled={busy}>Reverse</button>}</div></td></tr>)}{!data.items?.length&&<tr><td colSpan="8" className="finance-empty">No transactions found.</td></tr>}</tbody></table><ServerPager pagination={data.pagination} onPage={p=>loadList(pagerKind,p).catch(e=>setMsg(e?.response?.data?.error||e.message))}/></div>;

  return <section className="finance-page">
    <div className="finance-title-row"><div><h1>Finance</h1><p>Income, expenses, accounts and authoritative financial transactions.</p></div></div>
    <div className="module-top-tabs">{tabs.map(([key,label])=><button type="button" key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}</div>
    {msg&&<div className="finance-message">{msg}</div>}

    {tab==='overview'&&<>
      <div className="finance-stat-grid">
        <div className="finance-stat"><span>Today Income</span><strong>{money(dashboard.todayIncome)}</strong></div><div className="finance-stat"><span>Today Expenses</span><strong>{money(dashboard.todayExpense)}</strong></div><div className="finance-stat"><span>Month Income</span><strong>{money(dashboard.monthIncome)}</strong></div><div className="finance-stat"><span>Month Expenses</span><strong>{money(dashboard.monthExpense)}</strong></div><div className="finance-stat"><span>Cash Balance</span><strong>{money(dashboard.cashBalance)}</strong></div><div className="finance-stat"><span>Bank Balance</span><strong>{money(dashboard.bankBalance)}</strong></div><div className="finance-stat finance-stat-wide"><span>Net Position</span><strong>{money(dashboard.netPosition)}</strong><small>{Number(dashboard.netPosition||0)>=0?'Surplus':'Deficit'}</small></div>
      </div>
      <div className="finance-panel"><div className="finance-panel-head"><h3>Recent Transactions</h3></div><div className="finance-table-wrap"><table className="finance-table"><thead><tr><th>Date</th><th>No.</th><th>Type</th><th>Head</th><th>Account</th><th className="right">Amount</th></tr></thead><tbody>{(dashboard.recent||[]).map(x=><tr key={x._id}><td>{fmtDate(x.transactionDate)}</td><td>{x.transactionNo}</td><td>{x.type.replace('_',' ')}</td><td>{x.headId?.name||'—'}</td><td>{x.accountId?.name||x.fromAccountId?.name||'—'}</td><td className="right">{money(x.amount)}</td></tr>)}{!dashboard.recent?.length&&<tr><td colSpan="6" className="finance-empty">No posted transactions yet.</td></tr>}</tbody></table></div></div>
    </>}

    {(tab==='income'||tab==='expenses')&&<>
      <div className="finance-toolbar"><div className="finance-filters"><input placeholder="Search transaction / reference" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/><select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">All Statuses</option><option value="draft">Draft</option><option value="pending_approval">Pending Approval</option><option value="approved">Approved</option><option value="posted">Posted</option><option value="reversed">Reversed</option></select><button type="button" onClick={()=>loadList(tab,1)}>Search</button></div>{canManage&&<button type="button" className="finance-primary" onClick={()=>startEntry(tab==='income'?'income':'expense')}>+ Add {tab==='income'?'Income':'Expense'}</button>}</div>
      {transactionTable(tab==='income'?income:expenses,tab)}
    </>}

    {tab==='accounts'&&<>
      <div className="finance-toolbar"><h2>Financial Accounts</h2><div className="finance-toolbar-actions">{canSetup&&<button type="button" onClick={()=>setShowHead(true)}>+ Add Head</button>}{canSetup&&<button type="button" className="finance-primary" onClick={()=>setShowAccount(true)}>+ Add Account</button>}</div></div>
      <div className="finance-account-grid">{accounts.map(a=><button type="button" className="finance-account-card" key={a._id} onClick={()=>openLedger(a)}><span>{a.type.replace('_',' ')}</span><strong>{a.name}</strong><b>{money(a.currentBalance)}</b>{a.bankName&&<small>{a.bankName}{a.accountNumber?` • ${a.accountNumber}`:''}</small>}</button>)}</div>
      <div className="finance-panel"><div className="finance-panel-head"><h3>Income & Expense Heads</h3></div><div className="finance-head-columns"><div><h4>Income Heads</h4>{heads.filter(h=>h.type==='income').map(h=><div className="finance-head-row" key={h._id}><span>{h.name}</span><small>{h.code}{h.isSystem?' • System':''}</small></div>)}</div><div><h4>Expense Heads</h4>{heads.filter(h=>h.type==='expense').map(h=><div className="finance-head-row" key={h._id}><span>{h.name}</span><small>{h.code}{h.isSystem?' • System':''}</small></div>)}</div></div></div>
    </>}

    {tab==='transactions'&&<>
      <div className="finance-toolbar"><div className="finance-filters"><input placeholder="Search no. / reference / description" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/><select value={filters.type} onChange={e=>setFilters({...filters,type:e.target.value})}><option value="">All Types</option><option value="income">Income</option><option value="expense">Expense</option><option value="transfer">Transfer</option><option value="opening_balance">Opening Balance</option><option value="reversal">Reversal</option></select><select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">All Statuses</option><option value="draft">Draft</option><option value="pending_approval">Pending Approval</option><option value="approved">Approved</option><option value="posted">Posted</option><option value="reversed">Reversed</option></select><button type="button" onClick={()=>loadList('transactions',1)}>Search</button></div>{canManage&&<button type="button" className="finance-primary" onClick={()=>startEntry('transfer')}>+ Account Transfer</button>}</div>
      {transactionTable(transactions,'transactions')}
    </>}

    {tab==='reports'&&<section className="cms-report-workspace finance-report-workspace">
      <div className="cms-report-head"><div><h2>Finance Reports</h2><p>Income, expense and net financial activity for the selected date range and account.</p></div><button type="button" onClick={()=>window.print()}>Print Report</button></div>
      <div className="finance-toolbar cms-report-filterbar"><div className="finance-filters"><label><span>From</span><input type="date" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/></label><label><span>To</span><input type="date" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/></label><label><span>Account</span><select value={filters.accountId} onChange={e=>setFilters({...filters,accountId:e.target.value})}><option value="">All Accounts</option>{accounts.map(a=><option key={a._id} value={a._id}>{a.name}</option>)}</select></label><button type="button" onClick={loadReport}>Generate / View</button></div></div>
      <div className="finance-stat-grid finance-report-stats cms-report-kpis"><div className="finance-stat cms-report-kpi"><span>Income</span><strong>{money(report.income)}</strong></div><div className="finance-stat cms-report-kpi"><span>Expenses</span><strong>{money(report.expense)}</strong></div><div className="finance-stat cms-report-kpi"><span>Net</span><strong>{money(report.net)}</strong></div><div className="finance-stat cms-report-kpi"><span>Transactions</span><strong>{report.count||0}</strong></div></div>
      <div className="finance-panel cms-report-table-card"><div className="finance-panel-head cms-report-table-title"><div><h3>Income vs Expense Statement</h3><p>Financial activity matching the selected filters.</p></div></div><div className="finance-table-wrap cms-report-table-wrap"><table className="finance-table"><thead><tr><th>Date</th><th>No.</th><th>Type</th><th>Head</th><th>Account</th><th>Description</th><th className="right">Amount</th></tr></thead><tbody>{(report.rows||[]).map(x=><tr key={x._id}><td>{fmtDate(x.transactionDate)}</td><td>{x.transactionNo}</td><td>{x.type.replace('_',' ')}</td><td>{x.headId?.name||'—'}</td><td>{x.accountId?.name||x.fromAccountId?.name||'—'}</td><td>{x.description||x.referenceNo||'—'}</td><td className="right">{money(x.amount)}</td></tr>)}{!report.rows?.length&&<tr><td colSpan="7" className="cms-report-empty">No financial records found for the selected filters.</td></tr>}</tbody></table></div></div>
    </section>}

    {showEntry&&<div className="finance-modal-backdrop"><form className="finance-modal" onSubmit={saveEntry}><div className="finance-modal-head"><h3>{form.type==='income'?'Add Income':form.type==='expense'?'Add Expense':'Account Transfer'}</h3><button type="button" onClick={()=>setShowEntry(false)}>×</button></div><div className="finance-form-grid"><label>Date<input type="date" required value={form.transactionDate} onChange={e=>setForm({...form,transactionDate:e.target.value})}/></label>{form.type!=='transfer'?<><label>{form.type==='income'?'Income':'Expense'} Head<select required value={form.headId} onChange={e=>setForm({...form,headId:e.target.value})}><option value="">Select head</option>{activeHeads.filter(h=>h.type===form.type).map(h=><option key={h._id} value={h._id}>{h.name}</option>)}</select></label><label>Account<select required value={form.accountId} onChange={e=>setForm({...form,accountId:e.target.value})}><option value="">Select account</option>{accounts.filter(a=>a.isActive!==false).map(a=><option key={a._id} value={a._id}>{a.name}</option>)}</select></label></>:<><label>From Account<select required value={form.fromAccountId} onChange={e=>setForm({...form,fromAccountId:e.target.value})}><option value="">Select account</option>{accounts.filter(a=>a.isActive!==false).map(a=><option key={a._id} value={a._id}>{a.name}</option>)}</select></label><label>To Account<select required value={form.toAccountId} onChange={e=>setForm({...form,toAccountId:e.target.value})}><option value="">Select account</option>{accounts.filter(a=>a.isActive!==false).map(a=><option key={a._id} value={a._id}>{a.name}</option>)}</select></label></>}<label>Amount<input type="number" min="0.01" step="0.01" required value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Payment Method<select value={form.paymentMethod} onChange={e=>setForm({...form,paymentMethod:e.target.value})}><option value="cash">Cash</option><option value="bank_transfer">Bank Transfer</option><option value="cheque">Cheque</option><option value="online">Online / Digital</option><option value="card">Card</option><option value="other">Other</option></select></label>{form.type==='expense'&&<label>Payee<input value={form.payee} onChange={e=>setForm({...form,payee:e.target.value})}/></label>}<label>Reference No.<input value={form.referenceNo} onChange={e=>setForm({...form,referenceNo:e.target.value})}/></label><label className="span-2">Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div><div className="finance-modal-actions"><button type="button" onClick={()=>setShowEntry(false)}>Cancel</button><button type="submit" className="finance-primary" disabled={busy}>Save Draft</button></div></form></div>}

    {showAccount&&<div className="finance-modal-backdrop"><form className="finance-modal" onSubmit={createAccount}><div className="finance-modal-head"><h3>Add Finance Account</h3><button type="button" onClick={()=>setShowAccount(false)}>×</button></div><div className="finance-form-grid"><label>Account Name<input required value={accountForm.name} onChange={e=>setAccountForm({...accountForm,name:e.target.value})}/></label><label>Account Type<select value={accountForm.type} onChange={e=>setAccountForm({...accountForm,type:e.target.value})}><option value="cash">Cash</option><option value="petty_cash">Petty Cash</option><option value="bank">Bank</option></select></label><label>Opening Balance<input type="number" min="0" step="0.01" value={accountForm.openingBalance} onChange={e=>setAccountForm({...accountForm,openingBalance:e.target.value})}/></label><label>Opening Date<input type="date" value={accountForm.openingDate} onChange={e=>setAccountForm({...accountForm,openingDate:e.target.value})}/></label>{accountForm.type==='bank'&&<><label>Bank Name<input value={accountForm.bankName} onChange={e=>setAccountForm({...accountForm,bankName:e.target.value})}/></label><label>Account Number<input value={accountForm.accountNumber} onChange={e=>setAccountForm({...accountForm,accountNumber:e.target.value})}/></label><label>Bank Branch<input value={accountForm.bankBranch} onChange={e=>setAccountForm({...accountForm,bankBranch:e.target.value})}/></label></>}<label className="span-2">Description<textarea value={accountForm.description} onChange={e=>setAccountForm({...accountForm,description:e.target.value})}/></label></div><div className="finance-modal-actions"><button type="button" onClick={()=>setShowAccount(false)}>Cancel</button><button type="submit" className="finance-primary" disabled={busy}>Create Account</button></div></form></div>}

    {showHead&&<div className="finance-modal-backdrop"><form className="finance-modal finance-modal-small" onSubmit={createHead}><div className="finance-modal-head"><h3>Add Finance Head</h3><button type="button" onClick={()=>setShowHead(false)}>×</button></div><div className="finance-form-grid"><label>Type<select value={headForm.type} onChange={e=>setHeadForm({...headForm,type:e.target.value})}><option value="income">Income</option><option value="expense">Expense</option></select></label><label>Name<input required value={headForm.name} onChange={e=>setHeadForm({...headForm,name:e.target.value})}/></label><label>Code<input placeholder="Auto from name" value={headForm.code} onChange={e=>setHeadForm({...headForm,code:e.target.value})}/></label><label className="span-2">Description<textarea value={headForm.description} onChange={e=>setHeadForm({...headForm,description:e.target.value})}/></label></div><div className="finance-modal-actions"><button type="button" onClick={()=>setShowHead(false)}>Cancel</button><button type="submit" className="finance-primary" disabled={busy}>Add Head</button></div></form></div>}

    {ledger&&<div className="finance-modal-backdrop"><div className="finance-modal finance-ledger-modal"><div className="finance-modal-head"><div><h3>{ledger.account?.name} Ledger</h3><small>Current Balance: {money(ledger.currentBalance)}</small></div><button type="button" onClick={()=>setLedger(null)}>×</button></div><div className="finance-table-wrap"><table className="finance-table"><thead><tr><th>Date</th><th>Reference</th><th>Description</th><th className="right">Money In</th><th className="right">Money Out</th><th className="right">Balance</th></tr></thead><tbody>{(ledger.ledger||[]).map(x=><tr key={x._id}><td>{fmtDate(x.transactionDate)}</td><td>{x.transactionNo}</td><td>{x.description||x.referenceNo||x.type}</td><td className="right">{x.moneyIn?money(x.moneyIn):'—'}</td><td className="right">{x.moneyOut?money(x.moneyOut):'—'}</td><td className="right"><strong>{money(x.balance)}</strong></td></tr>)}</tbody></table></div><div className="finance-modal-actions"><button type="button" onClick={()=>window.print()}>Print</button><button type="button" className="finance-primary" onClick={()=>setLedger(null)}>Close</button></div></div></div>}
  </section>;
}
