import {useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'react-router-dom';
import api from '../../api/client';
import {useAuth} from '../../contexts/AuthContext';
import './notices.css';

const today=()=>new Date().toISOString().slice(0,10);
const fmtDate=v=>v?new Date(v).toLocaleDateString():'-';
const statusLabel=s=>String(s||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const errText=e=>e?.response?.data?.error||e?.response?.data?.message||e?.message||'Request failed';
const blank={title:'',categoryId:'',audience:'all',branchId:'',academicSessionId:'',targetProgramIds:[],targetSectionIds:[],employeeCategory:'',publishAt:today(),expireAt:'',priority:'normal',status:'draft',body:''};

export default function NoticesPage(){
  const {user}=useAuth();
  const [searchParams,setSearchParams]=useSearchParams();
  const [tab,setTabState]=useState(searchParams.get('tab')||'dashboard');
  const [meta,setMeta]=useState({categories:[],sessions:[],programs:[],sections:[],branches:[],settings:{}});
  const [dashboard,setDashboard]=useState({}),[notices,setNotices]=useState([]),[categories,setCategories]=useState([]),[settings,setSettings]=useState({});
  const [form,setForm]=useState(blank),[editing,setEditing]=useState(''),[showForm,setShowForm]=useState(false),[categoryName,setCategoryName]=useState('');
  const [filters,setFilters]=useState({status:'',categoryId:'',audience:'',from:'',to:'',search:''});
  const [msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
  const perms=new Set(user?.permissions||user?.effectivePermissions||[]);const can=p=>user?.systemRole==='platform_owner'||perms.has('*')||perms.has(p);
  const setTab=next=>{setTabState(next);setSearchParams(prev=>{const x=new URLSearchParams(prev);x.set('tab',next);return x;});};
  useEffect(()=>{const next=searchParams.get('tab')||'dashboard';if(next!==tab)setTabState(next)},[searchParams]);

  const filteredPrograms=useMemo(()=>meta.programs.filter(p=>!form.branchId||String(p.branchId?._id||p.branchId)===String(form.branchId)),[meta.programs,form.branchId]);
  const filteredSections=useMemo(()=>meta.sections.filter(s=>!form.targetProgramIds.length||form.targetProgramIds.includes(String(s.programId?._id||s.programId))),[meta.sections,form.targetProgramIds]);
  const displayNotices=useMemo(()=>notices.filter(n=>{const q=filters.search.trim().toLowerCase();return !q||`${n.noticeNo} ${n.title} ${n.body}`.toLowerCase().includes(q)}),[notices,filters.search]);

  async function loadMeta(){const {data}=await api.get('/notices/meta');setMeta(data||{});setCategories(data?.categories||[]);setSettings(data?.settings||{});}
  async function load(){
    try{setMsg('');await loadMeta();
      const dash=await api.get('/notices/dashboard');setDashboard(dash.data||{});
      if(can('MANAGE_NOTICES')){const p=new URLSearchParams();['status','categoryId','audience','from','to'].forEach(k=>filters[k]&&p.set(k,filters[k]));const r=await api.get(`/notices/manage${p.toString()?`?${p}`:''}`);setNotices(r.data||[])}else{const r=await api.get('/notices');setNotices(r.data||[])}
    }catch(e){setMsg(errText(e))}
  }
  useEffect(()=>{load()},[filters.status,filters.categoryId,filters.audience,filters.from,filters.to]);

  function openNew(){setEditing('');setForm({...blank,publishAt:today(),expireAt:settings.defaultValidityDays?new Date(Date.now()+Number(settings.defaultValidityDays)*86400000).toISOString().slice(0,10):''});setShowForm(true)}
  function openEdit(n){setEditing(n._id);setForm({title:n.title||'',categoryId:n.categoryId?._id||'',audience:n.audience||'all',branchId:n.branchId?._id||'',academicSessionId:n.academicSessionId?._id||'',targetProgramIds:(n.targetProgramIds||[]).map(x=>String(x._id||x)),targetSectionIds:(n.targetSectionIds||[]).map(x=>String(x._id||x)),employeeCategory:n.employeeCategory||'',publishAt:n.publishAt?String(n.publishAt).slice(0,10):today(),expireAt:n.expireAt?String(n.expireAt).slice(0,10):'',priority:n.priority||'normal',status:n.status||'draft',body:n.body||''});setShowForm(true)}
  async function saveNotice(e){e.preventDefault();setBusy(true);setMsg('');try{const payload={...form,targetProgramIds:form.audience==='program'?form.targetProgramIds:[],targetSectionIds:form.audience==='section'?form.targetSectionIds:[]};const r=editing?await api.put(`/notices/${editing}`,payload):await api.post('/notices',payload);setMsg(editing?'Notice updated.':'Notice created.');setShowForm(false);setEditing('');setForm(blank);await load();return r.data}catch(e2){setMsg(errText(e2))}finally{setBusy(false)}}
  async function uploadAttachment(id,file){if(!file)return;setBusy(true);try{const fd=new FormData();fd.append('attachment',file);await api.post(`/notices/${id}/attachment`,fd,{headers:{'Content-Type':'multipart/form-data'}});setMsg('Attachment uploaded.');await load()}catch(e){setMsg(errText(e))}finally{setBusy(false)}}
  async function publish(id){setBusy(true);try{const {data}=await api.post(`/notices/${id}/publish`);setMsg(data?.notice?.status==='scheduled'?'Notice scheduled.':`Notice published${data?.recipients!=null?` to ${data.recipients} user(s)`:''}.`);await load()}catch(e){setMsg(errText(e))}finally{setBusy(false)}}
  async function cancel(id){if(!confirm('Cancel this notice?'))return;setBusy(true);try{await api.post(`/notices/${id}/cancel`);setMsg('Notice cancelled.');await load()}catch(e){setMsg(errText(e))}finally{setBusy(false)}}
  async function addCategory(e){e.preventDefault();if(!categoryName.trim())return;try{await api.post('/notices/categories',{name:categoryName});setCategoryName('');setMsg('Category added.');await loadMeta()}catch(e2){setMsg(errText(e2))}}
  async function toggleCategory(c){try{await api.put(`/notices/categories/${c._id}`,{name:c.name,isActive:!c.isActive});await loadMeta()}catch(e){setMsg(errText(e))}}
  async function saveSettings(e){e.preventDefault();setBusy(true);try{const {data}=await api.put('/notices/settings',settings);setSettings(data);setMsg('Notice settings saved.')}catch(e2){setMsg(errText(e2))}finally{setBusy(false)}}

  const Nav=()=> <div className="notices-tabs">{[['dashboard','Dashboard'],['notices','Notices'],['categories','Categories'],['reports','Reports'],['settings','Settings']].map(([k,l])=><button type="button" key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{l}</button>)}</div>;
  const Filters=()=> <div className="notices-toolbar"><label className="grow">Search<input value={filters.search} onChange={e=>setFilters(x=>({...x,search:e.target.value}))} placeholder="Notice No, title or message..."/></label><label>Status<select value={filters.status} onChange={e=>setFilters(x=>({...x,status:e.target.value}))}><option value="">All</option>{['draft','scheduled','published','expired','cancelled'].map(x=><option key={x} value={x}>{statusLabel(x)}</option>)}</select></label><label>Category<select value={filters.categoryId} onChange={e=>setFilters(x=>({...x,categoryId:e.target.value}))}><option value="">All</option>{categories.map(c=><option key={c._id} value={c._id}>{c.name}</option>)}</select></label><label>Audience<select value={filters.audience} onChange={e=>setFilters(x=>({...x,audience:e.target.value}))}><option value="">All</option>{['all','students','employees','program','section','employee_category'].map(x=><option key={x} value={x}>{statusLabel(x)}</option>)}</select></label></div>;

  return <section className="notices-page"><h1>Notices</h1><Nav/>{msg&&<div className="notices-message">{msg}</div>}
    {tab==='dashboard'&&<><div className="notices-cards">{[['Total',dashboard.total],['Published',dashboard.active],['Scheduled',dashboard.scheduled],['Expired',dashboard.expired],['Draft',dashboard.draft]].map(([l,v])=><div className="notice-card" key={l}><span>{l}</span><strong>{v||0}</strong></div>)}</div><div className="notice-dashboard-grid"><div className="notices-panel"><h3>Recent Notices</h3><div className="notice-mini-list">{(dashboard.recent||[]).map(n=><div className="notice-mini-item" key={n._id}><strong>{n.noticeNo} · {n.title}</strong><small>{statusLabel(n.status)} · {fmtDate(n.publishAt)}</small></div>)}{!dashboard.recent?.length&&<div className="notices-empty">No notices yet.</div>}</div></div><div className="notices-panel"><h3>Upcoming Scheduled</h3><div className="notice-mini-list">{(dashboard.upcoming||[]).map(n=><div className="notice-mini-item" key={n._id}><strong>{n.title}</strong><small>{fmtDate(n.publishAt)} · {n.categoryId?.name||'General'}</small></div>)}{!dashboard.upcoming?.length&&<div className="notices-empty">No scheduled notices.</div>}</div></div></div></>}

    {tab==='notices'&&<>{can('MANAGE_NOTICES')&&<div className="notices-toolbar"><div className="grow"></div><button onClick={openNew}>+ Create Notice</button></div>}{showForm&&<form className="notices-panel" onSubmit={saveNotice}><h3>{editing?'Edit Notice':'Create Notice'}</h3><div className="notices-form four"><label className="span2">Title<input required value={form.title} onChange={e=>setForm(x=>({...x,title:e.target.value}))}/></label><label>Category<select value={form.categoryId} onChange={e=>setForm(x=>({...x,categoryId:e.target.value}))}><option value="">General</option>{categories.filter(c=>c.isActive!==false).map(c=><option key={c._id} value={c._id}>{c.name}</option>)}</select></label><label>Priority<select value={form.priority} onChange={e=>setForm(x=>({...x,priority:e.target.value}))}><option value="normal">Normal</option><option value="important">Important</option><option value="urgent">Urgent</option></select></label>
    <label>Audience<select value={form.audience} onChange={e=>setForm(x=>({...x,audience:e.target.value,targetProgramIds:[],targetSectionIds:[]}))}>{[['all','All'],['students','Students'],['employees','Employees'],['program','Specific Program / Class'],['section','Specific Section'],['employee_category','Employee Category']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Branch<select value={form.branchId} onChange={e=>setForm(x=>({...x,branchId:e.target.value}))}><option value="">All Branches</option>{meta.branches.map(b=><option key={b._id} value={b._id}>{b.name}</option>)}</select></label>{['program','section'].includes(form.audience)&&<label>Session<select value={form.academicSessionId} onChange={e=>setForm(x=>({...x,academicSessionId:e.target.value}))}><option value="">All Sessions</option>{meta.sessions.map(s=><option key={s._id} value={s._id}>{s.name||s.sessionName||s.label}</option>)}</select></label>}{form.audience==='program'&&<label>Program / Class<select multiple value={form.targetProgramIds} onChange={e=>setForm(x=>({...x,targetProgramIds:[...e.target.selectedOptions].map(o=>o.value)}))}>{filteredPrograms.map(p=><option key={p._id} value={p._id}>{p.name}</option>)}</select></label>}{form.audience==='section'&&<><label>Program / Class<select multiple value={form.targetProgramIds} onChange={e=>setForm(x=>({...x,targetProgramIds:[...e.target.selectedOptions].map(o=>o.value)}))}>{filteredPrograms.map(p=><option key={p._id} value={p._id}>{p.name}</option>)}</select></label><label>Section<select multiple value={form.targetSectionIds} onChange={e=>setForm(x=>({...x,targetSectionIds:[...e.target.selectedOptions].map(o=>o.value)}))}>{filteredSections.map(s=><option key={s._id} value={s._id}>{s.name||s.sectionName||s.code}</option>)}</select></label></>}{form.audience==='employee_category'&&<label>Employee Category<select required value={form.employeeCategory} onChange={e=>setForm(x=>({...x,employeeCategory:e.target.value}))}><option value="">Select</option><option value="academic_staff">Academic Staff</option><option value="non_teaching_staff">Non-Teaching Staff</option></select></label>}
    <label>Publish Date<input required type="date" value={form.publishAt} onChange={e=>setForm(x=>({...x,publishAt:e.target.value}))}/></label><label>Expiry Date<input type="date" value={form.expireAt} onChange={e=>setForm(x=>({...x,expireAt:e.target.value}))}/></label><label>Status<select value={form.status} onChange={e=>setForm(x=>({...x,status:e.target.value}))}><option value="draft">Draft</option>{settings.allowScheduledPublishing!==false&&<option value="scheduled">Scheduled</option>}<option value="published">Published</option></select></label><label className="span4">Notice / Message<textarea required value={form.body} onChange={e=>setForm(x=>({...x,body:e.target.value}))}/></label></div><div className="notices-actions"><button type="button" className="secondary" onClick={()=>setShowForm(false)}>Close</button><button disabled={busy}>{editing?'Save Changes':'Create Notice'}</button></div></form>}
    <Filters/><div className="notices-table-wrap"><table><thead><tr><th>Notice No</th><th>Title</th><th>Category</th><th>Audience</th><th>Publish</th><th>Expiry</th><th>Priority</th><th>Status</th><th>Actions</th></tr></thead><tbody>{displayNotices.map(n=><tr key={n._id}><td>{n.noticeNo}</td><td><strong>{n.title}</strong>{n.attachmentUrl&&<div><a href={n.attachmentUrl} target="_blank" rel="noreferrer">Attachment</a></div>}</td><td>{n.categoryId?.name||'General'}</td><td>{statusLabel(n.audience)}</td><td>{fmtDate(n.publishAt)}</td><td>{fmtDate(n.expireAt)}</td><td><span className={`notice-priority ${n.priority}`}>{statusLabel(n.priority)}</span></td><td><span className={`notice-badge ${n.status}`}>{statusLabel(n.status)}</span></td><td className="row-actions">{can('MANAGE_NOTICES')&&['draft','scheduled'].includes(n.status)&&<button className="secondary" onClick={()=>openEdit(n)}>Edit</button>}{can('SEND_NOTICES')&&['draft','scheduled'].includes(n.status)&&<button onClick={()=>publish(n._id)}>Publish</button>}{can('MANAGE_NOTICES')&&settings.allowAttachments!==false&&['draft','scheduled'].includes(n.status)&&<label className="secondary" style={{padding:'5px 8px',cursor:'pointer'}}>Attach<input type="file" hidden accept=".pdf,.jpg,.jpeg,.png,.webp,.doc,.docx" onChange={e=>uploadAttachment(n._id,e.target.files?.[0])}/></label>}{can('MANAGE_NOTICES')&&!['expired','cancelled'].includes(n.status)&&<button className="danger" onClick={()=>cancel(n._id)}>Cancel</button>}</td></tr>)}{!displayNotices.length&&<tr><td colSpan="9" className="notices-empty">No notices found.</td></tr>}</tbody></table></div></>}

    {tab==='categories'&&<><div className="notices-panel"><h3>Notice Categories</h3>{can('MANAGE_NOTICES')&&<form className="notices-toolbar" onSubmit={addCategory}><label className="grow">Category Name<input value={categoryName} onChange={e=>setCategoryName(e.target.value)} placeholder="Add new category..."/></label><button>Add Category</button></form>}</div><div className="notices-table-wrap"><table><thead><tr><th>Category</th><th>Type</th><th>Status</th><th>Action</th></tr></thead><tbody>{categories.map(c=><tr key={c._id}><td>{c.name}</td><td>{c.isSystem?'System Default':'Custom'}</td><td><span className={`notice-badge ${c.isActive?'published':'cancelled'}`}>{c.isActive?'Active':'Inactive'}</span></td><td>{can('MANAGE_NOTICES')&&<button className="secondary" onClick={()=>toggleCategory(c)}>{c.isActive?'Deactivate':'Activate'}</button>}</td></tr>)}</tbody></table></div></>}

    {tab==='reports'&&<section className="cms-report-workspace notices-report-workspace"><div className="cms-report-head"><div><h3>Notice Reports</h3><p>Notice register with category, audience, publication dates, expiry dates and current status.</p></div><button className="secondary" onClick={()=>window.print()}>Print Report</button></div><div className="notices-toolbar cms-report-filterbar"><Filters/><label><span>From</span><input type="date" value={filters.from} onChange={e=>setFilters(x=>({...x,from:e.target.value}))}/></label><label><span>To</span><input type="date" value={filters.to} onChange={e=>setFilters(x=>({...x,to:e.target.value}))}/></label></div><div className="cms-report-kpis"><div className="cms-report-kpi"><span>Report Records</span><strong>{displayNotices.length}</strong><small>Notices matching current filters</small></div></div><div className="cms-report-table-card"><div className="cms-report-table-title"><div><h4>Notice Register</h4><p>Filtered publication history.</p></div></div><div className="notices-table-wrap cms-report-table-wrap"><table><thead><tr><th>Notice No</th><th>Title</th><th>Category</th><th>Audience</th><th>Publish Date</th><th>Expiry Date</th><th>Status</th></tr></thead><tbody>{displayNotices.map(n=><tr key={n._id}><td>{n.noticeNo}</td><td>{n.title}</td><td>{n.categoryId?.name||'General'}</td><td>{statusLabel(n.audience)}</td><td>{fmtDate(n.publishAt)}</td><td>{fmtDate(n.expireAt)}</td><td>{statusLabel(n.status)}</td></tr>)}{!displayNotices.length&&<tr><td colSpan="7" className="notices-empty cms-report-empty">No report records found.</td></tr>}</tbody></table></div></div></section>}

    {tab==='settings'&&<form className="notices-panel notices-settings" onSubmit={saveSettings}><h3>Notice Settings</h3><div className="notices-form four"><label className="check"><input type="checkbox" checked={settings.enabled!==false} onChange={e=>setSettings(x=>({...x,enabled:e.target.checked}))}/> Notices Module Enabled</label><label className="check"><input type="checkbox" checked={settings.allowScheduledPublishing!==false} onChange={e=>setSettings(x=>({...x,allowScheduledPublishing:e.target.checked}))}/> Allow Scheduled Publishing</label><label className="check"><input type="checkbox" checked={!!settings.requireExpiryDate} onChange={e=>setSettings(x=>({...x,requireExpiryDate:e.target.checked}))}/> Require Expiry Date</label><label className="check"><input type="checkbox" checked={settings.allowAttachments!==false} onChange={e=>setSettings(x=>({...x,allowAttachments:e.target.checked}))}/> Allow Attachments</label><label>Default Validity Days<input type="number" min="1" max="3650" value={settings.defaultValidityDays||30} onChange={e=>setSettings(x=>({...x,defaultValidityDays:Number(e.target.value)}))}/></label><label className="check"><input type="checkbox" checked={!!settings.allowEmployeesToCreate} onChange={e=>setSettings(x=>({...x,allowEmployeesToCreate:e.target.checked}))}/> Allow Employees to Create</label><label className="check"><input type="checkbox" checked={!!settings.requireApprovalBeforePublishing} onChange={e=>setSettings(x=>({...x,requireApprovalBeforePublishing:e.target.checked}))}/> Require Approval Before Publishing</label></div>{can('MANAGE_NOTICES')&&<div className="notices-actions"><button disabled={busy}>Save Settings</button></div>}</form>}
  </section>;
}
