import {useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'react-router-dom';
import api from '../../api/client';
import {useAuth} from '../../contexts/AuthContext';
import './payroll.css';

const now=new Date();
const money=v=>Number(v||0).toLocaleString(undefined,{maximumFractionDigits:2});
const dateInput=v=>v?String(v).slice(0,10):'';
const errText=e=>e?.response?.data?.error||e?.response?.data?.message||e?.message||'Request failed';
const monthName=m=>new Date(2000,Number(m||1)-1,1).toLocaleString(undefined,{month:'long'});
const statusLabel=s=>String(s||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());

export default function PayrollPage(){
  const {user}=useAuth();
  const [searchParams,setSearchParams]=useSearchParams();
  const [tab,setTabState]=useState(searchParams.get('tab')||'dashboard');
  const [employees,setEmployees]=useState([]),[structures,setStructures]=useState([]),[records,setRecords]=useState([]),[adjustments,setAdjustments]=useState([]),[payments,setPayments]=useState([]),[loans,setLoans]=useState([]);
  const [dashboard,setDashboard]=useState({}),[settings,setSettings]=useState({}),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
  const [filters,setFilters]=useState({year:now.getFullYear(),month:now.getMonth()+1,branchId:'',category:''});
  const [salaryForm,setSalaryForm]=useState({employeeId:'',basicSalary:'',effectiveFrom:dateInput(new Date()),allowance1Name:'House Rent',allowance1Value:'',allowance2Name:'Conveyance',allowance2Value:'',deductionName:'',deductionValue:''});
  const [adjustForm,setAdjustForm]=useState({employeeId:'',year:now.getFullYear(),month:now.getMonth()+1,type:'bonus',amount:'',reason:''});
  const [paymentForm,setPaymentForm]=useState({payrollRecordId:'',amount:'',paymentDate:dateInput(new Date()),paymentMethod:'bank',referenceNo:'',remarks:''});
  const [loanForm,setLoanForm]=useState({employeeId:'',type:'advance',principalAmount:'',monthlyDeduction:'',startMonth:`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`,reason:''});
  const perms=new Set(user?.permissions||user?.effectivePermissions||[]);const can=p=>user?.systemRole==='platform_owner'||perms.has('*')||perms.has(p);
  const setTab=next=>{setTabState(next);setSearchParams(prev=>{const copy=new URLSearchParams(prev);copy.set('tab',next);return copy;});};
  useEffect(()=>{const next=searchParams.get('tab')||'dashboard';if(next!==tab)setTabState(next);},[searchParams]);

  const branches=useMemo(()=>{const map=new Map();employees.forEach(e=>{const b=e.branchId;if(b?._id)map.set(String(b._id),b)});return [...map.values()];},[employees]);
  const filteredRecords=useMemo(()=>records.filter(r=>(!filters.branchId||String(r.employeeId?.branchId?._id||r.employeeId?.branchId)===String(filters.branchId))&&(!filters.category||r.employeeId?.category===filters.category)),[records,filters.branchId,filters.category]);
  const payableRecords=useMemo(()=>records.filter(r=>['posted','approved','partially_paid'].includes(r.status)&&Number((r.balanceAmount??r.netSalary)||0)>0),[records]);
  const payrollEnabled=settings.enabled!==false;

  async function load(){
    try{
      setMsg('');
      const q=`?year=${filters.year}&month=${filters.month}`;
      const [e,s,r,a,p,d,st,l]=await Promise.all([api.get('/payroll/employees'),api.get('/payroll/salary-structures'),api.get(`/payroll/records${q}`),api.get(`/payroll/adjustments${q}`),api.get('/payroll/payments'),api.get(`/payroll/dashboard${q}${filters.branchId?`&branchId=${filters.branchId}`:''}${filters.category?`&category=${filters.category}`:''}`),api.get('/payroll/settings'),api.get('/payroll/loans')]);
      setEmployees(e.data||[]);setStructures(s.data||[]);setRecords(r.data||[]);setAdjustments(a.data||[]);setPayments(p.data||[]);setDashboard(d.data||{});setSettings(st.data||{});setLoans(l.data||[]);
    }catch(e){setMsg(errText(e));}
  }
  useEffect(()=>{load();},[filters.year,filters.month,filters.branchId,filters.category]);

  async function saveSalary(e){e.preventDefault();setBusy(true);setMsg('');try{const components=[];if(salaryForm.allowance1Name&&salaryForm.allowance1Value)components.push({name:salaryForm.allowance1Name,type:'allowance',calculation:'fixed',value:Number(salaryForm.allowance1Value)});if(salaryForm.allowance2Name&&salaryForm.allowance2Value)components.push({name:salaryForm.allowance2Name,type:'allowance',calculation:'fixed',value:Number(salaryForm.allowance2Value)});if(salaryForm.deductionName&&salaryForm.deductionValue)components.push({name:salaryForm.deductionName,type:'deduction',calculation:'fixed',value:Number(salaryForm.deductionValue)});await api.post('/payroll/salary-structures',{employeeId:salaryForm.employeeId,basicSalary:Number(salaryForm.basicSalary),effectiveFrom:salaryForm.effectiveFrom,components});setMsg('Salary structure saved.');setSalaryForm(x=>({...x,employeeId:'',basicSalary:'',allowance1Value:'',allowance2Value:'',deductionName:'',deductionValue:''}));await load();}catch(e){setMsg(errText(e));}finally{setBusy(false)}}
  async function generate(){if(!payrollEnabled){setMsg('Payroll is disabled in Payroll Settings.');return}setBusy(true);setMsg('');try{const r=await api.post('/payroll/generate',{year:Number(filters.year),month:Number(filters.month),branchId:filters.branchId||undefined,category:filters.category||undefined});const skipped=[];if(r.data?.skippedLocked)skipped.push(`${r.data.skippedLocked} locked`);if(r.data?.skippedNoStructure)skipped.push(`${r.data.skippedNoStructure} without salary structure`);if(r.data?.skippedNotJoined)skipped.push(`${r.data.skippedNotJoined} not yet joined`);setMsg(`${r.data?.count||0} payroll record(s) ${settings.requireApproval===false?'generated and posted':'generated'}${skipped.length?`; skipped ${skipped.join(', ')}`:''}.`);await load();}catch(e){setMsg(errText(e));}finally{setBusy(false)}}
  async function postPayroll(id){setBusy(true);try{await api.post(`/payroll/records/${id}/post`);setMsg('Payroll posted.');await load();}catch(e){setMsg(errText(e));}finally{setBusy(false)}}
  async function addAdjustment(e){e.preventDefault();setBusy(true);try{await api.post('/payroll/adjustments',{...adjustForm,year:Number(adjustForm.year),month:Number(adjustForm.month),amount:Number(adjustForm.amount)});setMsg('Adjustment added. Regenerate payroll to include it.');setAdjustForm(x=>({...x,amount:'',reason:''}));await load();}catch(e){setMsg(errText(e));}finally{setBusy(false)}}
  async function removeAdjustment(id){if(!confirm('Remove this adjustment?'))return;try{await api.delete(`/payroll/adjustments/${id}`);await load();}catch(e){setMsg(errText(e));}}
  async function paySalary(e){e.preventDefault();setBusy(true);try{await api.post('/payroll/payments',{...paymentForm,amount:Number(paymentForm.amount)});setMsg('Salary payment posted.');setPaymentForm(x=>({...x,payrollRecordId:'',amount:'',referenceNo:'',remarks:''}));await load();}catch(e){setMsg(errText(e));}finally{setBusy(false)}}
  async function saveSettings(e){e.preventDefault();setBusy(true);try{await api.put('/payroll/settings',settings);setMsg('Payroll settings saved.');await load();}catch(e){setMsg(errText(e));}finally{setBusy(false)}}
  async function requestLoan(e){e.preventDefault();setBusy(true);setMsg('');try{await api.post('/payroll/loans',{...loanForm,principalAmount:Number(loanForm.principalAmount),monthlyDeduction:Number(loanForm.monthlyDeduction)});setMsg(`${loanForm.type==='loan'?'Loan':'Salary advance'} request created.`);setLoanForm(x=>({...x,employeeId:'',principalAmount:'',monthlyDeduction:'',reason:''}));await load();}catch(e){setMsg(errText(e));}finally{setBusy(false)}}
  async function approveLoan(id){const item=loans.find(x=>x._id===id);if(!item)return;const raw=prompt('Approved amount',String(item.principalAmount||''));if(raw===null)return;const approvedAmount=Number(raw);const installmentRaw=prompt('Monthly recovery',String(item.monthlyDeduction||''));if(installmentRaw===null)return;const monthlyDeduction=Number(installmentRaw);setBusy(true);try{await api.post(`/payroll/loans/${id}/approve`,{approvedAmount,monthlyDeduction,startMonth:item.startMonth});setMsg('Loan / advance approved and activated.');await load();}catch(e){setMsg(errText(e));}finally{setBusy(false)}}
  async function rejectLoan(id){if(!confirm('Reject this loan / advance request?'))return;setBusy(true);try{await api.post(`/payroll/loans/${id}/reject`,{});setMsg('Loan / advance request rejected.');await load();}catch(e){setMsg(errText(e));}finally{setBusy(false)}}
  async function cancelLoan(id){if(!confirm('Cancel this loan / advance?'))return;setBusy(true);try{await api.post(`/payroll/loans/${id}/cancel`,{});setMsg('Loan / advance cancelled.');await load();}catch(e){setMsg(errText(e));}finally{setBusy(false)}}

  async function printPayslip(id){try{const {data}=await api.get(`/payroll/records/${id}/payslip`);const w=window.open('','_blank','width=850,height=900');if(!w)return;const a=(data.allowances||[]).map(x=>`<tr><td>${x.name}</td><td style="text-align:right">${money(x.amount)}</td></tr>`).join('');const d=(data.deductions||[]).map(x=>`<tr><td>${x.name}</td><td style="text-align:right">${money(x.amount)}</td></tr>`).join('');w.document.write(`<html><head><title>Payslip</title><style>body{font-family:Arial;padding:28px;color:#172033}h2{text-align:center;margin:0 0 4px}.sub{text-align:center;color:#60708a;margin-bottom:24px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:8px 28px;margin-bottom:18px}table{width:100%;border-collapse:collapse;margin-top:12px}td,th{border:1px solid #d8e0ea;padding:8px}th{background:#f2f6fb}.total{font-weight:700}.footer{text-align:center;margin-top:32px;color:#666}</style></head><body><h2>Salary Payslip</h2><div class="sub">${monthName(data.month)} ${data.year}</div><div class="grid"><div><b>Employee:</b> ${data.employeeId?.name||''}</div><div><b>Code:</b> ${data.employeeId?.employeeNo||data.employeeId?.employeeCode||''}</div><div><b>Designation:</b> ${data.employeeId?.designationId?.name||''}</div><div><b>Branch:</b> ${data.employeeId?.branchId?.name||''}</div></div><table><tr><th>Particular</th><th>Amount</th></tr><tr><td>Basic Salary</td><td style="text-align:right">${money(data.basicSalary)}</td></tr>${a}<tr class="total"><td>Gross Salary</td><td style="text-align:right">${money(data.grossSalary)}</td></tr>${d}<tr class="total"><td>Net Salary</td><td style="text-align:right">${money(data.netSalary)}</td></tr><tr><td>Paid</td><td style="text-align:right">${money(data.paidAmount)}</td></tr><tr><td>Balance</td><td style="text-align:right">${money(data.balanceAmount??data.netSalary)}</td></tr></table><div class="footer">${data.settings?.payslipFooter||''}</div><script>window.onload=()=>window.print()</script></body></html>`);w.document.close();}catch(e){setMsg(errText(e));}}

  const FilterBar=()=> <div className="payroll-filterbar"><label>Month<select value={filters.month} onChange={e=>setFilters(x=>({...x,month:Number(e.target.value)}))}>{Array.from({length:12},(_,i)=><option key={i+1} value={i+1}>{monthName(i+1)}</option>)}</select></label><label>Year<input type="number" value={filters.year} onChange={e=>setFilters(x=>({...x,year:Number(e.target.value)}))}/></label><label>Branch<select value={filters.branchId} onChange={e=>setFilters(x=>({...x,branchId:e.target.value}))}><option value="">All Branches</option>{branches.map(b=><option key={b._id} value={b._id}>{b.name||b.code}</option>)}</select></label><label>Category<select value={filters.category} onChange={e=>setFilters(x=>({...x,category:e.target.value}))}><option value="">All Categories</option><option value="academic_staff">Academic Staff</option><option value="non_teaching_staff">Non-Teaching Staff</option></select></label></div>;

  return <section className="payroll-page">{!payrollEnabled&&tab!=='settings'&&<div className="payroll-alert">Payroll is disabled in Payroll Settings. Existing records remain viewable, but payroll changes are blocked.</div>}
    <h1>Payroll</h1>
    {msg&&<div className="payroll-message">{msg}</div>}
    <div className="module-top-tabs payroll-tabs">{[['dashboard','Dashboard'],['salary','Salary Structure'],['payroll','Payroll'],['loans','Loans & Advances'],['adjustments','Adjustments'],['payments','Payments'],['reports','Reports'],['settings','Settings']].map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{l}</button>)}</div>

    {tab==='dashboard'&&<><FilterBar/><div className="payroll-cards">{[['Total Employees',dashboard.totalEmployees],['Current Payroll',dashboard.employees],['Gross Payroll',money(dashboard.gross)],['Deductions',money(dashboard.deductions)],['Net Payable',money(dashboard.net)],['Paid',money(dashboard.paid)],['Unpaid',money(dashboard.unpaid)],['Pending Payroll',dashboard.pendingPayroll]].map(([l,v])=><div className="payroll-stat" key={l}><span>{l}</span><strong>{v||0}</strong></div>)}</div></>}

    {tab==='salary'&&<><div className="payroll-panel"><h3>Salary Structure</h3>{can('MANAGE_SALARY_STRUCTURES')&&<form onSubmit={saveSalary} className="payroll-form four"><label>Employee<select required value={salaryForm.employeeId} onChange={e=>setSalaryForm(x=>({...x,employeeId:e.target.value}))}><option value="">Select Employee</option>{employees.map(e=><option key={e._id} value={e._id}>{e.employeeNo||e.employeeCode} - {e.name}</option>)}</select></label><label>Basic Salary<input type="number" min="0" required value={salaryForm.basicSalary} onChange={e=>setSalaryForm(x=>({...x,basicSalary:e.target.value}))}/></label><label>Effective From<input type="date" required value={salaryForm.effectiveFrom} onChange={e=>setSalaryForm(x=>({...x,effectiveFrom:e.target.value}))}/></label><div></div><label>Allowance 1<input value={salaryForm.allowance1Name} onChange={e=>setSalaryForm(x=>({...x,allowance1Name:e.target.value}))}/></label><label>Amount<input type="number" min="0" value={salaryForm.allowance1Value} onChange={e=>setSalaryForm(x=>({...x,allowance1Value:e.target.value}))}/></label><label>Allowance 2<input value={salaryForm.allowance2Name} onChange={e=>setSalaryForm(x=>({...x,allowance2Name:e.target.value}))}/></label><label>Amount<input type="number" min="0" value={salaryForm.allowance2Value} onChange={e=>setSalaryForm(x=>({...x,allowance2Value:e.target.value}))}/></label><label>Fixed Deduction<input placeholder="e.g. Loan Installment" value={salaryForm.deductionName} onChange={e=>setSalaryForm(x=>({...x,deductionName:e.target.value}))}/></label><label>Amount<input type="number" min="0" value={salaryForm.deductionValue} onChange={e=>setSalaryForm(x=>({...x,deductionValue:e.target.value}))}/></label><div className="payroll-actions"><button disabled={busy||!payrollEnabled}>Save Structure</button></div></form>}</div><div className="payroll-table-wrap"><table><thead><tr><th>Employee</th><th>Designation</th><th>Branch</th><th>Basic</th><th>Allowances</th><th>Deductions</th><th>Effective From</th><th>Status</th></tr></thead><tbody>{structures.map(s=><tr key={s._id}><td>{s.employeeId?.employeeNo||s.employeeId?.employeeCode} - {s.employeeId?.name}</td><td>{s.employeeId?.designationId?.name||'-'}</td><td>{s.employeeId?.branchId?.name||'-'}</td><td>{money(s.basicSalary)}</td><td>{money((s.components||[]).filter(c=>c.type==='allowance').reduce((a,c)=>a+Number(c.value||0),0))}</td><td>{money((s.components||[]).filter(c=>c.type==='deduction').reduce((a,c)=>a+Number(c.value||0),0))}</td><td>{dateInput(s.effectiveFrom)}</td><td><span className={`payroll-badge ${s.isActive?'active':'inactive'}`}>{s.isActive?'Active':'Inactive'}</span></td></tr>)}{!structures.length&&<tr><td colSpan="8" className="empty">No salary structures found.</td></tr>}</tbody></table></div></>}

    {tab==='payroll'&&<><div className="payroll-toolbar"><FilterBar/>{can('GENERATE_PAYROLL')&&<button onClick={generate} disabled={busy||!payrollEnabled}>Generate / Regenerate Payroll</button>}</div><div className="payroll-table-wrap"><table><thead><tr><th>Employee</th><th>Designation</th><th>Basic</th><th>Allowances</th><th>Deductions</th><th>Gross</th><th>Net</th><th>Status</th><th>Action</th></tr></thead><tbody>{filteredRecords.map(r=><tr key={r._id}><td>{r.employeeId?.employeeNo||r.employeeId?.employeeCode} - {r.employeeId?.name}</td><td>{r.employeeId?.designationId?.name||'-'}</td><td>{money(r.basicSalary)}</td><td>{money((r.allowances||[]).reduce((s,x)=>s+Number(x.amount||0),0))}</td><td>{money(r.totalDeductions)}</td><td>{money(r.grossSalary)}</td><td>{money(r.netSalary)}</td><td><span className={`payroll-badge ${r.status}`}>{statusLabel(r.status)}</span></td><td className="row-actions">{r.status==='generated'&&can('APPROVE_PAYROLL')&&<button disabled={!payrollEnabled} onClick={()=>postPayroll(r._id)}>{settings.requireApproval===false?'Post Legacy Record':'Post'}</button>}<button className="secondary" onClick={()=>printPayslip(r._id)}>Payslip</button></td></tr>)}{!filteredRecords.length&&<tr><td colSpan="9" className="empty">No payroll records for this month.</td></tr>}</tbody></table></div></>}


    {tab==='loans'&&<><div className="payroll-panel"><h3>Loans & Salary Advances</h3>{can('MANAGE_PAYROLL')&&<form onSubmit={requestLoan} className="payroll-form six"><label>Employee<select required value={loanForm.employeeId} onChange={e=>setLoanForm(x=>({...x,employeeId:e.target.value}))}><option value="">Select Employee</option>{employees.map(e=><option key={e._id} value={e._id}>{e.employeeNo||e.employeeCode} - {e.name}</option>)}</select></label><label>Type<select value={loanForm.type} onChange={e=>setLoanForm(x=>({...x,type:e.target.value}))}><option value="advance">Salary Advance</option><option value="loan">Loan</option></select></label><label>Requested Amount<input required type="number" min="1" step="0.01" value={loanForm.principalAmount} onChange={e=>setLoanForm(x=>({...x,principalAmount:e.target.value}))}/></label><label>Monthly Recovery<input required type="number" min="1" step="0.01" value={loanForm.monthlyDeduction} onChange={e=>setLoanForm(x=>({...x,monthlyDeduction:e.target.value}))}/></label><label>Recovery Starts<input required type="month" value={loanForm.startMonth} onChange={e=>setLoanForm(x=>({...x,startMonth:e.target.value}))}/></label><label>Reason<input value={loanForm.reason} onChange={e=>setLoanForm(x=>({...x,reason:e.target.value}))}/></label><div className="payroll-actions"><button disabled={busy||!payrollEnabled}>Create Request</button></div></form>}</div><div className="payroll-table-wrap"><table><thead><tr><th>Employee</th><th>Type</th><th>Requested</th><th>Approved</th><th>Monthly Recovery</th><th>Outstanding</th><th>Start Month</th><th>Status</th><th>Action</th></tr></thead><tbody>{loans.map(l=><tr key={l._id}><td>{l.employeeId?.employeeNo||l.employeeId?.employeeCode} - {l.employeeId?.name}</td><td>{l.type==='loan'?'Loan':'Salary Advance'}</td><td>{money(l.principalAmount)}</td><td>{money(l.approvedAmount)}</td><td>{money(l.monthlyDeduction)}</td><td>{money(l.outstandingAmount)}</td><td>{l.startMonth||'-'}</td><td><span className={`payroll-badge ${l.status}`}>{statusLabel(l.status)}</span></td><td className="row-actions">{can('MANAGE_PAYROLL')&&l.status==='pending'&&<><button disabled={!payrollEnabled||busy} onClick={()=>approveLoan(l._id)}>Approve</button><button className="danger" disabled={!payrollEnabled||busy} onClick={()=>rejectLoan(l._id)}>Reject</button></>}{can('MANAGE_PAYROLL')&&['pending','approved','active'].includes(l.status)&&!(l.recoveryHistory||[]).length&&<button className="secondary" disabled={!payrollEnabled||busy} onClick={()=>cancelLoan(l._id)}>Cancel</button>}</td></tr>)}{!loans.length&&<tr><td colSpan="9" className="empty">No loans or salary advances found.</td></tr>}</tbody></table></div></>}

    {tab==='adjustments'&&<><div className="payroll-panel"><h3>Monthly Adjustment</h3>{can('MANAGE_PAYROLL')&&<form onSubmit={addAdjustment} className="payroll-form six"><label>Employee<select required value={adjustForm.employeeId} onChange={e=>setAdjustForm(x=>({...x,employeeId:e.target.value}))}><option value="">Select Employee</option>{employees.map(e=><option key={e._id} value={e._id}>{e.employeeNo||e.employeeCode} - {e.name}</option>)}</select></label><label>Month<select value={adjustForm.month} onChange={e=>setAdjustForm(x=>({...x,month:Number(e.target.value)}))}>{Array.from({length:12},(_,i)=><option key={i+1} value={i+1}>{monthName(i+1)}</option>)}</select></label><label>Year<input type="number" value={adjustForm.year} onChange={e=>setAdjustForm(x=>({...x,year:Number(e.target.value)}))}/></label><label>Type<select value={adjustForm.type} onChange={e=>setAdjustForm(x=>({...x,type:e.target.value}))}><option value="bonus">Bonus</option><option value="allowance">Allowance</option><option value="deduction">Deduction</option><option value="fine">Fine</option><option value="advance">Manual Advance Adjustment</option><option value="loan_recovery">Manual Loan Adjustment</option><option value="other">Other</option></select></label><label>Amount<input required type="number" min="1" value={adjustForm.amount} onChange={e=>setAdjustForm(x=>({...x,amount:e.target.value}))}/></label><label>Reason<input required value={adjustForm.reason} onChange={e=>setAdjustForm(x=>({...x,reason:e.target.value}))}/></label><div className="payroll-actions"><button disabled={busy||!payrollEnabled}>Add Adjustment</button></div></form>}</div><div className="payroll-table-wrap"><table><thead><tr><th>Employee</th><th>Month</th><th>Type</th><th>Amount</th><th>Reason</th><th>Action</th></tr></thead><tbody>{adjustments.map(a=><tr key={a._id}><td>{a.employeeId?.employeeNo||a.employeeId?.employeeCode} - {a.employeeId?.name}</td><td>{monthName(a.month)} {a.year}</td><td>{statusLabel(a.type)}</td><td>{money(a.amount)}</td><td>{a.reason}</td><td>{can('MANAGE_PAYROLL')&&<button className="danger" onClick={()=>removeAdjustment(a._id)}>Remove</button>}</td></tr>)}{!adjustments.length&&<tr><td colSpan="6" className="empty">No adjustments for this month.</td></tr>}</tbody></table></div></>}

    {tab==='payments'&&<><div className="payroll-panel"><h3>Salary Payment</h3>{can('MARK_PAYROLL_PAID')&&<form onSubmit={paySalary} className="payroll-form six"><label>Employee / Payroll<select required value={paymentForm.payrollRecordId} onChange={e=>{const id=e.target.value,r=payableRecords.find(x=>x._id===id);setPaymentForm(x=>({...x,payrollRecordId:id,amount:r?String((r.balanceAmount??r.netSalary)||''):''}))}}><option value="">Select Posted Payroll</option>{payableRecords.map(r=><option key={r._id} value={r._id}>{r.employeeId?.employeeNo||r.employeeId?.employeeCode} - {r.employeeId?.name} | {monthName(r.month)} {r.year} | Balance {money(r.balanceAmount??r.netSalary)}</option>)}</select></label><label>Amount Paid<input required type="number" min="0.01" step="0.01" max={payableRecords.find(r=>r._id===paymentForm.payrollRecordId)?.balanceAmount??undefined} value={paymentForm.amount} onChange={e=>setPaymentForm(x=>({...x,amount:e.target.value}))}/></label><label>Payment Date<input required type="date" value={paymentForm.paymentDate} onChange={e=>setPaymentForm(x=>({...x,paymentDate:e.target.value}))}/></label><label>Method<select value={paymentForm.paymentMethod} onChange={e=>setPaymentForm(x=>({...x,paymentMethod:e.target.value}))}><option value="cash">Cash</option><option value="bank">Bank</option><option value="cheque">Cheque</option><option value="online">Online Transfer</option></select></label><label>Reference No<input value={paymentForm.referenceNo} onChange={e=>setPaymentForm(x=>({...x,referenceNo:e.target.value}))}/></label><label>Remarks<input value={paymentForm.remarks} onChange={e=>setPaymentForm(x=>({...x,remarks:e.target.value}))}/></label><div className="payroll-actions"><button disabled={busy||!payrollEnabled}>Post Payment</button></div></form>}</div><div className="payroll-table-wrap"><table><thead><tr><th>Date</th><th>Employee</th><th>Payroll Month</th><th>Amount</th><th>Method</th><th>Reference</th></tr></thead><tbody>{payments.map(p=><tr key={p._id}><td>{dateInput(p.paymentDate)}</td><td>{p.employeeId?.employeeNo||p.employeeId?.employeeCode} - {p.employeeId?.name}</td><td>{monthName(p.payrollRecordId?.month)} {p.payrollRecordId?.year}</td><td>{money(p.amount)}</td><td>{statusLabel(p.paymentMethod)}</td><td>{p.referenceNo||'-'}</td></tr>)}{!payments.length&&<tr><td colSpan="6" className="empty">No salary payments found.</td></tr>}</tbody></table></div></>}

    {tab==='reports'&&<section className="cms-report-workspace payroll-report-workspace"><div className="cms-report-head"><div><h3>Payroll Reports</h3><p>{monthName(filters.month)} {filters.year} payroll summary with employee-wise gross salary, deductions, net salary and payment status.</p></div><button className="secondary" onClick={()=>window.print()}>Print Report</button></div><div className="payroll-toolbar cms-report-filterbar"><FilterBar/></div><div className="payroll-report-summary cms-report-kpis"><div className="cms-report-kpi"><span>Gross Salary</span><strong>{money(filteredRecords.reduce((s,r)=>s+Number(r.grossSalary||0),0))}</strong></div><div className="cms-report-kpi"><span>Deductions</span><strong>{money(filteredRecords.reduce((s,r)=>s+Number(r.totalDeductions||0),0))}</strong></div><div className="cms-report-kpi"><span>Net Salary</span><strong>{money(filteredRecords.reduce((s,r)=>s+Number(r.netSalary||0),0))}</strong></div><div className="cms-report-kpi"><span>Paid</span><strong>{money(filteredRecords.reduce((s,r)=>s+Number(r.paidAmount||0),0))}</strong></div><div className="cms-report-kpi"><span>Employees</span><strong>{filteredRecords.length}</strong></div></div><div className="cms-report-table-card"><div className="cms-report-table-title"><div><h4>Employee Payroll Statement</h4><p>{monthName(filters.month)} {filters.year}</p></div></div><div className="payroll-table-wrap cms-report-table-wrap"><table><thead><tr><th>Employee</th><th>Branch</th><th>Gross</th><th>Deductions</th><th>Net</th><th>Paid</th><th>Balance</th><th>Status</th></tr></thead><tbody>{filteredRecords.map(r=><tr key={r._id}><td>{r.employeeId?.employeeNo||r.employeeId?.employeeCode} - {r.employeeId?.name}</td><td>{r.employeeId?.branchId?.name||'-'}</td><td>{money(r.grossSalary)}</td><td>{money(r.totalDeductions)}</td><td>{money(r.netSalary)}</td><td>{money(r.paidAmount)}</td><td>{money(r.balanceAmount??r.netSalary)}</td><td>{statusLabel(r.status)}</td></tr>)}{!filteredRecords.length&&<tr><td colSpan="8" className="cms-report-empty">No payroll records found for the selected filters.</td></tr>}</tbody></table></div></div></section>}

    {tab==='settings'&&<form className="payroll-panel payroll-settings" onSubmit={saveSettings}><h3>Payroll Settings</h3><div className="payroll-form four"><label className="check"><input type="checkbox" checked={settings.enabled!==false} onChange={e=>setSettings(x=>({...x,enabled:e.target.checked}))}/> Payroll Enabled</label><label>Salary Calculation Day<input type="number" min="1" max="31" value={settings.salaryCalculationDay||30} onChange={e=>setSettings(x=>({...x,salaryCalculationDay:Number(e.target.value)}))}/></label><label className="check"><input type="checkbox" checked={!!settings.attendanceDeductionEnabled} onChange={e=>setSettings(x=>({...x,attendanceDeductionEnabled:e.target.checked}))}/> Deduct Recorded Absences</label><label>Per-Day Salary Divisor<select value={settings.perDayDeductionMethod||'30_days'} onChange={e=>setSettings(x=>({...x,perDayDeductionMethod:e.target.value}))}><option value="30_days">30 Days</option><option value="working_days">College Working Days</option></select></label><label className="check"><input type="checkbox" checked={settings.allowPartialPayment!==false} onChange={e=>setSettings(x=>({...x,allowPartialPayment:e.target.checked}))}/> Allow Partial Payment</label><label className="check"><input type="checkbox" checked={settings.requireApproval!==false} onChange={e=>setSettings(x=>({...x,requireApproval:e.target.checked}))}/> Require Payroll Approval</label><div className="payroll-setting-note">{settings.requireApproval===false?'Generated payroll will be posted automatically and can proceed directly to payment.':'Generated payroll must be posted by an authorized user before payment.'}</div><div className="payroll-setting-note span2">Unpaid leave is deducted only for the portion falling inside the selected payroll month. When absence deduction is enabled, recorded staff absences already covered by unpaid leave are not deducted twice.</div><label className="span2">Payslip Footer<input value={settings.payslipFooter||''} onChange={e=>setSettings(x=>({...x,payslipFooter:e.target.value}))}/></label></div>{can('MANAGE_PAYROLL')&&<div className="payroll-actions"><button disabled={busy}>Save Settings</button></div>}</form>}
  </section>;
}
