const College=require('../../models/College');
const FeedbackSurvey=require('../../models/FeedbackSurvey');
const FeedbackResponse=require('../../models/FeedbackResponse');
const Student=require('../../models/Student');
const Employee=require('../../models/Employee');
const User=require('../../models/User');
const Notification=require('../../models/Notification');
const AcademicSession=require('../../models/AcademicSession');
const Program=require('../../models/Program');
const Section=require('../../models/Section');
const push=require('../../services/pushNotificationService');
const feedbackAnalytics=require('./analytics');

const sid=v=>String(v?._id||v||'');
const activeWindow=()=>({status:'published',startsAt:{$lte:new Date()},$or:[{closesAt:null},{closesAt:{$exists:false}},{closesAt:{$gte:new Date()}}]});
function respondentType(user){if(user?.linkedStudentId)return 'student';const roles=new Set((user?.roleCodes||[]).map(x=>String(x).toLowerCase()));if(user?.linkedEmployeeId&&roles.has('teacher'))return 'teacher';return null;}
async function targetUsers(collegeId,survey){
  const ids=[];
  if(['students','both'].includes(survey.audience)){
    const q={collegeId,status:'active'};
    if(survey.academicSessionId)q.academicSessionId=survey.academicSessionId;
    if(survey.programIds?.length)q.programId={$in:survey.programIds};
    if(survey.sectionIds?.length)q.sectionId={$in:survey.sectionIds};
    const students=await Student.find(q).select('_id').lean();
    const users=await User.find({collegeId,isActive:true,linkedStudentId:{$in:students.map(x=>x._id)}}).select('_id').lean();
    ids.push(...users.map(x=>x._id));
  }
  if(['teachers','both'].includes(survey.audience)){
    const employees=await Employee.find({collegeId,isActive:true,category:'academic_staff'}).select('_id').lean();
    const users=await User.find({collegeId,isActive:true,linkedEmployeeId:{$in:employees.map(x=>x._id)}}).populate('roleIds','code name').select('_id roleIds').lean();
    ids.push(...users.filter(u=>(u.roleIds||[]).some(r=>String(r.code||r.name||'').toLowerCase()==='teacher')).map(x=>x._id));
  }
  return [...new Set(ids.map(String))];
}
async function eligibilityContext(req){
  const type=respondentType(req.user);if(!type)return{type:null,student:null};
  if(type!=='student')return{type,student:null};
  const student=await Student.findOne(req.tenantFilter({_id:req.user.linkedStudentId,status:'active'})).select('academicSessionId programId sectionId').lean();
  return{type,student};
}
function eligibleFromContext(context,survey){const type=context.type;if(!type)return false;if(type==='student'&&!['students','both'].includes(survey.audience))return false;if(type==='teacher'&&!['teachers','both'].includes(survey.audience))return false;if(type==='student'){
  const student=context.student;if(!student)return false;
  if(survey.academicSessionId&&sid(student.academicSessionId)!==sid(survey.academicSessionId))return false;
  if(survey.programIds?.length&&!survey.programIds.some(x=>sid(x)===sid(student.programId)))return false;
  if(survey.sectionIds?.length&&!survey.sectionIds.some(x=>sid(x)===sid(student.sectionId)))return false;
}return true;}
async function eligible(req,survey){return eligibleFromContext(await eligibilityContext(req),survey);}
function cleanQuestions(qs=[]){return qs.map((q,i)=>({prompt:String(q.prompt||'').trim(),type:q.type,required:q.required!==false,options:q.type==='multiple_choice'?(q.options||[]).map(x=>String(x).trim()).filter(Boolean):[],order:i})).filter(q=>q.prompt&&['rating','multiple_choice','yes_no','text'].includes(q.type));}
exports.meta=async(req,res)=>{const [sessions,programs,sections]=await Promise.all([AcademicSession.find(req.tenantFilter({})).sort({startDate:-1}).select('name sessionName isCurrent').lean(),Program.find(req.tenantFilter({})).sort({name:1}).select('name code academicSessionId').lean(),Section.find(req.tenantFilter({})).sort({name:1}).select('name code programId academicSessionId').lean()]);res.json({sessions,programs,sections});};
exports.list=async(req,res)=>{const surveys=await FeedbackSurvey.find(req.tenantFilter({})).sort({createdAt:-1}).lean();const counts=await FeedbackResponse.aggregate([{$match:{collegeId:req.user.collegeId,surveyId:{$in:surveys.map(x=>x._id)}}},{$group:{_id:'$surveyId',count:{$sum:1}}}]);const map=new Map(counts.map(x=>[String(x._id),x.count]));res.json({surveys:surveys.map(x=>({...x,responseCount:map.get(String(x._id))||0}))});};
exports.create=async(req,res)=>{const questions=cleanQuestions(req.body.questions);if(!questions.length)return res.status(400).json({error:'Add at least one feedback question'});const doc=await FeedbackSurvey.create({collegeId:req.collegeId,title:req.body.title,description:req.body.description||'',audience:req.body.audience||'students',academicSessionId:req.body.academicSessionId||null,programIds:req.body.programIds||[],sectionIds:req.body.sectionIds||[],mandatory:Boolean(req.body.mandatory),anonymous:req.body.anonymous!==false,startsAt:req.body.startsAt||new Date(),closesAt:req.body.closesAt||null,questions,createdBy:req.user._id});res.status(201).json({survey:doc});};
exports.update=async(req,res)=>{const doc=await FeedbackSurvey.findOne(req.tenantFilter({_id:req.params.id}));if(!doc)return res.status(404).json({error:'Feedback not found'});if(doc.status!=='draft')return res.status(409).json({error:'Only draft feedback can be edited'});const questions=cleanQuestions(req.body.questions);if(!questions.length)return res.status(400).json({error:'Add at least one feedback question'});Object.assign(doc,{title:req.body.title,description:req.body.description||'',audience:req.body.audience||'students',academicSessionId:req.body.academicSessionId||null,programIds:req.body.programIds||[],sectionIds:req.body.sectionIds||[],mandatory:Boolean(req.body.mandatory),anonymous:req.body.anonymous!==false,startsAt:req.body.startsAt||new Date(),closesAt:req.body.closesAt||null,questions});await doc.save();res.json({survey:doc});};
exports.publish=async(req,res)=>{const doc=await FeedbackSurvey.findOne(req.tenantFilter({_id:req.params.id}));if(!doc)return res.status(404).json({error:'Feedback not found'});if(!doc.questions.length)return res.status(400).json({error:'Feedback has no questions'});doc.status='published';doc.publishedAt=new Date();await doc.save();const userIds=await targetUsers(req.collegeId,doc);if(userIds.length){const title=doc.mandatory?'Mandatory Feedback Required':'New Feedback Available';const message=doc.mandatory?`Please complete “${doc.title}” before continuing to the portal.`:`“${doc.title}” is now available.`;await Notification.insertMany(userIds.map(userId=>({collegeId:req.collegeId,userId,type:'feedback',title,message,entityType:'FeedbackSurvey',entityId:doc._id})),{ordered:false}).catch(()=>{});push.sendToUsers(req.collegeId,{_id:{$in:userIds}},{title,body:message,data:{type:'feedback',surveyId:String(doc._id),mandatory:doc.mandatory}}).catch(()=>{});}res.json({survey:doc,targeted:userIds.length});};
exports.close=async(req,res)=>{const doc=await FeedbackSurvey.findOneAndUpdate(req.tenantFilter({_id:req.params.id}),{$set:{status:'closed'}},{new:true});if(!doc)return res.status(404).json({error:'Feedback not found'});res.json({survey:doc});};
exports.analytics=async(req,res)=>{const survey=await FeedbackSurvey.findOne(req.tenantFilter({_id:req.params.id})).lean();if(!survey)return res.status(404).json({error:'Feedback not found'});const responses=await FeedbackResponse.find(req.tenantFilter({surveyId:survey._id})).lean();const targeted=(await targetUsers(req.collegeId,survey)).length;const analytics=survey.questions.map(q=>{const vals=responses.map(r=>r.answers.find(a=>sid(a.questionId)===sid(q._id))?.value).filter(v=>v!==undefined&&v!==null&&v!=='');if(q.type==='rating'){const nums=vals.map(Number).filter(n=>n>=1&&n<=5);const dist=[1,2,3,4,5].map(n=>({value:n,count:nums.filter(x=>x===n).length}));return{questionId:q._id,prompt:q.prompt,type:q.type,responses:nums.length,average:nums.length?Number((nums.reduce((a,b)=>a+b,0)/nums.length).toFixed(2)):null,distribution:dist};}if(q.type==='yes_no'||q.type==='multiple_choice'){const counts={};vals.forEach(v=>counts[String(v)]=(counts[String(v)]||0)+1);return{questionId:q._id,prompt:q.prompt,type:q.type,responses:vals.length,distribution:Object.entries(counts).map(([value,count])=>({value,count}))};}return{questionId:q._id,prompt:q.prompt,type:q.type,responses:vals.length,comments:vals.map(String)};});const ratingAverages=analytics.filter(x=>x.type==='rating'&&x.average!==null).map(x=>x.average);const breakdowns=await feedbackAnalytics.build(req.collegeId,survey,responses);const college=await College.findById(req.collegeId).select('name code address contactNo email website logoUrl educationalSlogan').lean();res.json({college,survey,targeted,responseCount:responses.length,responseRate:targeted?Number((responses.length/targeted*100).toFixed(1)):0,overallRating:ratingAverages.length?Number((ratingAverages.reduce((a,b)=>a+b,0)/ratingAverages.length).toFixed(2)):null,analytics,...breakdowns});};
exports.available=async(req,res)=>{const docs=await FeedbackSurvey.find(req.tenantFilter(activeWindow())).sort({mandatory:-1,startsAt:1}).lean();const [submitted,context]=await Promise.all([FeedbackResponse.find(req.tenantFilter({respondentUserId:req.user._id,surveyId:{$in:docs.map(x=>x._id)}})).select('surveyId submittedAt').lean(),eligibilityContext(req)]);const done=new Map(submitted.map(x=>[sid(x.surveyId),x.submittedAt]));const out=[];for(const survey of docs)if(eligibleFromContext(context,survey))out.push({...survey,submitted:Boolean(done.get(sid(survey._id))),submittedAt:done.get(sid(survey._id))||null});res.json({surveys:out});};
exports.pendingMandatory=async(req,res)=>{const docs=await FeedbackSurvey.find(req.tenantFilter({...activeWindow(),mandatory:true})).sort({startsAt:1}).lean();const context=await eligibilityContext(req);const eligibleDocs=docs.filter(survey=>eligibleFromContext(context,survey));if(!eligibleDocs.length)return res.json({pending:false,survey:null});const submitted=await FeedbackResponse.find(req.tenantFilter({respondentUserId:req.user._id,surveyId:{$in:eligibleDocs.map(x=>x._id)}})).select('surveyId').lean();const done=new Set(submitted.map(x=>sid(x.surveyId)));const survey=eligibleDocs.find(item=>!done.has(sid(item._id)))||null;res.json({pending:Boolean(survey),survey});};
exports.submit=async(req,res)=>{const survey=await FeedbackSurvey.findOne(req.tenantFilter({_id:req.params.id,...activeWindow()}));if(!survey)return res.status(404).json({error:'Feedback is not available'});if(!(await eligible(req,survey)))return res.status(403).json({error:'You are not in the audience for this feedback'});const existing=await FeedbackResponse.exists(req.tenantFilter({surveyId:survey._id,respondentUserId:req.user._id}));if(existing)return res.status(409).json({error:'Feedback already submitted'});const incoming=new Map((req.body.answers||[]).map(a=>[sid(a.questionId),a.value]));const answers=[];for(const q of survey.questions){let value=incoming.get(sid(q._id));if(q.required&&(value===undefined||value===null||String(value).trim()===''))return res.status(400).json({error:`Please answer: ${q.prompt}`});if(q.type==='rating'&&value!==undefined){value=Number(value);if(value<1||value>5)return res.status(400).json({error:`Rating must be 1–5: ${q.prompt}`});}if(q.type==='multiple_choice'&&value&&!q.options.includes(String(value)))return res.status(400).json({error:`Invalid option: ${q.prompt}`});if(q.type==='yes_no'&&value&&!['Yes','No'].includes(String(value)))return res.status(400).json({error:`Invalid answer: ${q.prompt}`});answers.push({questionId:q._id,value});}const response=await FeedbackResponse.create({collegeId:req.collegeId,surveyId:survey._id,respondentUserId:req.user._id,respondentType:respondentType(req.user),answers});res.status(201).json({response:{id:response._id,submittedAt:response.submittedAt}});};
exports.enforceMandatory=async(req,res,next)=>{try{const type=respondentType(req.user);if(!type)return next();const docs=await FeedbackSurvey.find(req.tenantFilter({...activeWindow(),mandatory:true})).select('_id audience academicSessionId programIds sectionIds title').lean();const context=await eligibilityContext(req);const eligibleDocs=docs.filter(survey=>eligibleFromContext(context,survey));if(!eligibleDocs.length)return next();const submitted=await FeedbackResponse.find(req.tenantFilter({respondentUserId:req.user._id,surveyId:{$in:eligibleDocs.map(x=>x._id)}})).select('surveyId').lean();const done=new Set(submitted.map(x=>sid(x.surveyId)));const pending=eligibleDocs.find(item=>!done.has(sid(item._id)));if(pending)return res.status(428).json({error:'Mandatory feedback must be completed before continuing',code:'MANDATORY_FEEDBACK_REQUIRED',surveyId:pending._id,title:pending.title});next();}catch(e){next(e);}};
