const Role = require('../models/Role');
const P = require('../constants/permissions');

const ROLE_DEFINITION_VERSION = 2;

const DEFAULT_ROLES = [
  ['Director', 'director', ['*'], true],
  ['Principal', 'principal', [
    P.VIEW_ADMISSIONS, P.MANAGE_ADMISSIONS, P.APPROVE_ADMISSIONS, P.MANAGE_STUDENT_LIFECYCLE,
    P.VIEW_STUDENTS, P.MANAGE_STUDENTS, P.VIEW_EMPLOYEES, P.MANAGE_EMPLOYEES,
    P.VIEW_ACADEMICS, P.MANAGE_ACADEMICS, P.VIEW_ATTENDANCE, P.MARK_ATTENDANCE, P.CORRECT_ATTENDANCE,
    P.VIEW_EXAMS, P.MANAGE_EXAMS, P.VERIFY_EXAM_MARKS, P.PUBLISH_RESULTS, P.MANAGE_GRADING, P.VIEW_RESULT_REPORTS,
    P.VIEW_LIBRARY, P.VIEW_TRANSPORT, P.VIEW_HOSTEL, P.VIEW_PAYROLL,
    P.VIEW_NOTICES, P.MANAGE_NOTICES, P.SEND_NOTICES, P.VIEW_COMMUNICATION_REPORTS,
    P.VIEW_FINANCE, P.APPROVE_FINANCE_TRANSACTION, P.POST_FINANCE_TRANSACTION, P.VIEW_FINANCE_REPORTS,
    P.VIEW_EVENTS, P.MANAGE_EVENTS, P.MANAGE_EVENT_REGISTRATIONS, P.VIEW_EVENT_REPORTS,
    P.VIEW_REPORTS
  ], true],
  ['Admin', 'admin', [
    P.MANAGE_USERS, P.MANAGE_USER_ROLES,
    P.VIEW_ADMISSIONS, P.MANAGE_ADMISSIONS, P.APPROVE_ADMISSIONS, P.MANAGE_STUDENT_LIFECYCLE,
    P.VIEW_STUDENTS, P.MANAGE_STUDENTS, P.VIEW_EMPLOYEES, P.MANAGE_EMPLOYEES,
    P.VIEW_ACADEMICS, P.MANAGE_ACADEMICS, P.VIEW_ATTENDANCE, P.MARK_ATTENDANCE, P.CORRECT_ATTENDANCE,
    P.MANAGE_BIOMETRIC, P.VIEW_FEES, P.VIEW_FINANCE, P.CREATE_FINANCE_TRANSACTION, P.VIEW_FINANCE_REPORTS,
    P.VIEW_EXAMS, P.VIEW_LIBRARY, P.VIEW_TRANSPORT, P.VIEW_HOSTEL, P.VIEW_PAYROLL,
    P.VIEW_NOTICES, P.MANAGE_NOTICES, P.SEND_NOTICES, P.VIEW_COMMUNICATION_REPORTS,
    P.VIEW_EVENTS, P.VIEW_REPORTS
  ], true],
  ['Employee', 'employee', [P.VIEW_NOTICES, P.VIEW_EVENTS], true],
  ['Teacher', 'teacher', [
    P.VIEW_STUDENTS, P.VIEW_ACADEMICS, P.VIEW_ATTENDANCE, P.MARK_ATTENDANCE,
    P.VIEW_EXAMS, P.ENTER_EXAM_MARKS, P.VIEW_RESULT_REPORTS,
    P.VIEW_NOTICES, P.VIEW_EVENTS
  ], true],
  ['Accountant', 'accountant', [
    P.VIEW_FEES, P.MANAGE_FEES, P.RECEIVE_FEE_PAYMENTS, P.VOID_FEE_PAYMENTS,
    P.POST_FEE_PAYMENTS, P.LOCK_FEE_PACKAGE, P.VIEW_FEE_AUDIT,
    P.VIEW_FINANCE, P.CREATE_FINANCE_TRANSACTION, P.MANAGE_FINANCE_ACCOUNTS, P.MANAGE_FINANCE_HEADS,
    P.VIEW_FINANCE_REPORTS, P.MANAGE_EXPENSES,
    P.VIEW_PAYROLL, P.MANAGE_PAYROLL, P.MANAGE_EMPLOYEE_CONTRACTS, P.MANAGE_SALARY_STRUCTURES,
    P.MANAGE_EMPLOYEE_LEAVE, P.APPROVE_EMPLOYEE_LEAVE, P.MANAGE_EMPLOYEE_LOANS,
    P.GENERATE_PAYROLL, P.APPROVE_PAYROLL, P.MARK_PAYROLL_PAID, P.VIEW_PAYROLL_REPORTS,
    P.VIEW_REPORTS
  ], true],
  ['Librarian', 'librarian', [
    P.VIEW_STUDENTS, P.VIEW_LIBRARY, P.MANAGE_LIBRARY, P.ISSUE_LIBRARY_BOOKS,
    P.RETURN_LIBRARY_BOOKS, P.MANAGE_LIBRARY_FINES, P.MANAGE_LIBRARY_SETTINGS,
    P.VIEW_LIBRARY_REPORTS, P.VIEW_REPORTS
  ], true],
  ['Exam Controller', 'exam_controller', [
    P.VIEW_STUDENTS, P.VIEW_ACADEMICS, P.VIEW_EXAMS, P.MANAGE_EXAMS, P.ENTER_EXAM_MARKS,
    P.VERIFY_EXAM_MARKS, P.PUBLISH_RESULTS, P.MANAGE_GRADING, P.VIEW_RESULT_REPORTS, P.VIEW_REPORTS
  ], true],
  ['Hostel Warden', 'hostel_warden', [
    P.VIEW_STUDENTS, P.VIEW_HOSTEL, P.MANAGE_HOSTEL, P.MANAGE_HOSTELS,
    P.MANAGE_HOSTEL_ROOMS, P.MANAGE_HOSTEL_ALLOCATIONS, P.MANAGE_HOSTEL_MESS,
    P.MANAGE_HOSTEL_COMPLAINTS, P.VIEW_HOSTEL_REPORTS, P.VIEW_NOTICES, P.VIEW_EVENTS, P.VIEW_REPORTS
  ], true],
  ['Transport Manager', 'transport_manager', [
    P.VIEW_STUDENTS, P.VIEW_EMPLOYEES, P.VIEW_TRANSPORT, P.MANAGE_TRANSPORT,
    P.MANAGE_TRANSPORT_VEHICLES, P.MANAGE_TRANSPORT_ROUTES, P.MANAGE_TRANSPORT_ASSIGNMENTS,
    P.MANAGE_TRANSPORT_MAINTENANCE, P.VIEW_TRANSPORT_REPORTS, P.VIEW_NOTICES, P.VIEW_EVENTS, P.VIEW_REPORTS
  ], true],
  ['Event Manager', 'event_manager', [
    P.VIEW_STUDENTS, P.VIEW_EMPLOYEES, P.VIEW_NOTICES, P.VIEW_EVENTS,
    P.MANAGE_EVENTS, P.MANAGE_EVENT_REGISTRATIONS, P.VIEW_EVENT_REPORTS
  ], true],
  ['ISA', 'isa', [P.VIEW_STUDENTS, P.VIEW_ACADEMICS, P.VIEW_ATTENDANCE, P.VIEW_NOTICES, P.VIEW_EVENTS], true],
  ['Student', 'student', [
    P.VIEW_ACADEMICS, P.VIEW_ATTENDANCE, P.VIEW_FEES, P.VIEW_EXAMS,
    P.VIEW_LIBRARY, P.VIEW_NOTICES, P.VIEW_EVENTS
  ], true]
];

async function seedDefaultRoles(collegeId) {
  const out = {};

  for (const [name, code, permissions, isProtected] of DEFAULT_ROLES) {
    let role = await Role.findOne({ collegeId, code });

    if (!role) {
      role = await Role.create({
        collegeId,
        name,
        code,
        permissions,
        isProtected,
        isActive: true,
        definitionVersion: ROLE_DEFINITION_VERSION
      });
    } else if (Number(role.definitionVersion || 0) < ROLE_DEFINITION_VERSION) {
      role.name = name;
      role.permissions = permissions;
      role.isProtected = isProtected;
      role.isActive = true;
      role.definitionVersion = ROLE_DEFINITION_VERSION;
      await role.save();
    }

    out[code] = role;
  }

  return out;
}

module.exports = { DEFAULT_ROLES, ROLE_DEFINITION_VERSION, seedDefaultRoles };
