import {useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'react-router-dom';
import api from '../../api/client';
import {useAuth} from '../../contexts/AuthContext';
import './transport.css';

const today=()=>new Date().toISOString().slice(0,10);
const money=v=>Number(v||0).toLocaleString();
const errText=e=>e?.response?.data?.error||e?.message||'Request failed';
const emptyVehicle={registrationNo:'',vehicleType:'bus',make:'',model:'',year:'',seatingCapacity:40,driverEmployeeId:'',conductorEmployeeId:'',insuranceExpiry:'',fitnessExpiry:'',permitExpiry:'',odometer:0,status:'active',notes:''};
const emptyRoute={name:'',vehicleId:'',startPoint:'',endPoint:'',defaultMonthlyFee:0,isActive:true,stops:[{name:'',pickupTime:'',dropTime:'',monthlyFee:'',landmark:''}]};
const emptyAssignment={academicSessionId:'',programId:'',studentId:'',routeId:'',stopId:'',startDate:today(),endDate:'',status:'active',monthlyFee:'',pickupType:'both',notes:''};
const emptyMaintenance={vehicleId:'',type:'service',serviceDate:today(),odometer:'',cost:'',vendor:'',nextDueDate:'',status:'completed',description:''};

function Pager({page,setPage,total,pageSize=10}){const pages=Math.max(1,Math.ceil(total/pageSize));if(total<=pageSize)return null;return <div className="transport-pager"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page} of {pages}</span><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>Next</button></div>}
function Field({label,children,help}){return <label className="transport-field"><span>{label}</span>{children}{help&&<small>{help}</small>}</label>}

export default function TransportPage(){
  const {user}=useAuth();
  const [searchParams,setSearchParams]=useSearchParams();
  const [tab,setTabState]=useState(searchParams.get('tab')||'dashboard');
  const setTab=next=>{setTabState(next);setSearchParams(prev=>{const copy=new URLSearchParams(prev);copy.set('tab',next);return copy;});};
  useEffect(()=>{const next=searchParams.get('tab')||'dashboard';if(next!==tab)setTabState(next);},[searchParams]);

  const [dashboard,setDashboard]=useState({});
  const [vehicles,setVehicles]=useState([]),[routes,setRoutes]=useState([]),[assignments,setAssignments]=useState([]),[maintenance,setMaintenance]=useState([]),[reportData,setReportData]=useState({summary:{},routes:[],vehicles:[],assignments:[],maintenance:[]});
  const [lookups,setLookups]=useState({sessions:[],programs:[],students:[],employees:[]});
  const [settings,setSettings]=useState({enforceCapacity:true,allowRouteChange:true,allowFeeOverride:true,maintenanceReminderDays:30,documentExpiryReminderDays:30});
  const [vehicleForm,setVehicleForm]=useState(emptyVehicle),[vehicleEdit,setVehicleEdit]=useState(null);
  const [routeForm,setRouteForm]=useState(emptyRoute),[routeEdit,setRouteEdit]=useState(null);
  const [assignmentForm,setAssignmentForm]=useState(emptyAssignment),[studentSearch,setStudentSearch]=useState('');
  const [maintenanceForm,setMaintenanceForm]=useState(emptyMaintenance);
  const [msg,setMsg]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [vehiclePage,setVehiclePage]=useState(1),[routePage,setRoutePage]=useState(1),[assignmentPage,setAssignmentPage]=useState(1),[maintenancePage,setMaintenancePage]=useState(1);
  const perms=new Set(user?.permissions||user?.effectivePermissions||[]);
  const can=p=>user?.systemRole==='platform_owner'||perms.has('*')||perms.has(p);

  async function load(){
    setError('');
    try{
      const [d,v,r,a,m,l,s,rep]=await Promise.all([api.get('/transport/dashboard'),api.get('/transport/vehicles'),api.get('/transport/routes'),api.get('/transport/assignments'),api.get('/transport/maintenance'),api.get('/transport/lookups'),api.get('/transport/settings'),api.get('/transport/report')]);
      setDashboard(d.data||{});setVehicles(v.data||[]);setRoutes(r.data||[]);setAssignments(a.data||[]);setMaintenance(m.data||[]);setLookups(l.data||{});setSettings(s.data||settings);setReportData(rep.data||{summary:{},routes:[],vehicles:[],assignments:[],maintenance:[]});
    }catch(e){setError(errText(e));}
  }
  useEffect(()=>{load();},[]);
  const flash=t=>{setMsg(t);setTimeout(()=>setMsg(''),2500)};
  async function run(fn,success){setBusy(true);setError('');try{await fn();flash(success);await load();return true}catch(e){setError(errText(e));return false}finally{setBusy(false)}}

  const employees=lookups.employees||[];
  const selectedRoute=routes.find(r=>r._id===assignmentForm.routeId);
  const selectedStop=selectedRoute?.stops?.find(s=>s._id===assignmentForm.stopId);
  const filteredStudents=useMemo(()=>{
    return (lookups.students||[]).filter(s=>(!assignmentForm.academicSessionId||String(s.academicSessionId)===assignmentForm.academicSessionId)&&(!assignmentForm.programId||String(s.programId)===assignmentForm.programId));
  },[lookups.students,assignmentForm.academicSessionId,assignmentForm.programId]);
  const studentOptions=filteredStudents.map(s=>({id:s._id,label:`${s.rollNo||s.registrationNo||s.admissionNo||'No Roll'} — ${s.name}${s.fatherName?` — ${s.fatherName}`:''}`}));
  const activeRoutes=routes.filter(r=>r.isActive&&r.vehicleId?.status==='active'&&(!settings.enforceCapacity||Number(r.vehicleId?.availableSeats??1)>0));

  async function saveVehicle(e){e.preventDefault();const data={...vehicleForm,year:vehicleForm.year||undefined,seatingCapacity:Number(vehicleForm.seatingCapacity),odometer:Number(vehicleForm.odometer||0),driverEmployeeId:vehicleForm.driverEmployeeId||null,conductorEmployeeId:vehicleForm.conductorEmployeeId||null};const ok=await run(()=>vehicleEdit?api.put(`/transport/vehicles/${vehicleEdit}`,data):api.post('/transport/vehicles',data),vehicleEdit?'Vehicle updated':'Vehicle added');if(ok){setVehicleForm(emptyVehicle);setVehicleEdit(null)}}
  function editVehicle(v){setVehicleEdit(v._id);setVehicleForm({registrationNo:v.registrationNo||'',vehicleType:v.vehicleType||'bus',make:v.make||'',model:v.model||'',year:v.year||'',seatingCapacity:v.seatingCapacity||1,driverEmployeeId:v.driverEmployeeId?._id||'',conductorEmployeeId:v.conductorEmployeeId?._id||'',insuranceExpiry:v.insuranceExpiry?.slice?.(0,10)||'',fitnessExpiry:v.fitnessExpiry?.slice?.(0,10)||'',permitExpiry:v.permitExpiry?.slice?.(0,10)||'',odometer:v.odometer||0,status:v.status||'active',notes:v.notes||''});window.scrollTo({top:0,behavior:'smooth'})}

  async function saveRoute(e){e.preventDefault();const stops=routeForm.stops.filter(s=>s.name.trim()).map((s,i)=>({...s,sequence:i+1,monthlyFee:s.monthlyFee===''?0:Number(s.monthlyFee)}));const data={...routeForm,vehicleId:routeForm.vehicleId||null,defaultMonthlyFee:Number(routeForm.defaultMonthlyFee||0),stops};const ok=await run(()=>routeEdit?api.put(`/transport/routes/${routeEdit}`,data):api.post('/transport/routes',data),routeEdit?'Route updated':'Route added');if(ok){setRouteForm(emptyRoute);setRouteEdit(null)}}
  function editRoute(r){setRouteEdit(r._id);setRouteForm({name:r.name||'',vehicleId:r.vehicleId?._id||'',startPoint:r.startPoint||'',endPoint:r.endPoint||'',defaultMonthlyFee:r.defaultMonthlyFee||0,isActive:r.isActive!==false,stops:(r.stops||[]).map(s=>({_id:s._id,name:s.name||'',pickupTime:s.pickupTime||'',dropTime:s.dropTime||'',monthlyFee:s.monthlyFee??'',landmark:s.landmark||''}))||emptyRoute.stops});window.scrollTo({top:0,behavior:'smooth'})}
  const updateStop=(i,key,value)=>setRouteForm(f=>({...f,stops:f.stops.map((s,idx)=>idx===i?{...s,[key]:value}:s)}));
  const addStop=()=>setRouteForm(f=>({...f,stops:[...f.stops,{name:'',pickupTime:'',dropTime:'',monthlyFee:'',landmark:''}]}));
  const removeStop=i=>setRouteForm(f=>({...f,stops:f.stops.filter((_,idx)=>idx!==i)}));

  function onStudentInput(value){setStudentSearch(value);const hit=studentOptions.find(x=>x.label===value);setAssignmentForm(f=>({...f,studentId:hit?.id||''}))}
  function onRouteChange(routeId){const r=routes.find(x=>x._id===routeId);setAssignmentForm(f=>({...f,routeId,stopId:'',monthlyFee:r?.defaultMonthlyFee??''}))}
  function onStopChange(stopId){const stop=selectedRoute?.stops?.find(s=>s._id===stopId);setAssignmentForm(f=>({...f,stopId,monthlyFee:stop?.monthlyFee||selectedRoute?.defaultMonthlyFee||0}))}
  async function saveAssignment(e){e.preventDefault();if(!assignmentForm.studentId)return setError('Select a student from the list');const data={...assignmentForm,monthlyFee:assignmentForm.monthlyFee===''?undefined:Number(assignmentForm.monthlyFee),endDate:assignmentForm.endDate||undefined};const ok=await run(()=>api.post('/transport/assignments',data),'Student assigned to transport');if(ok){setAssignmentForm(emptyAssignment);setStudentSearch('')}}
  async function endAssignment(id){if(!confirm('End this transport assignment and release the seat?'))return;await run(()=>api.post(`/transport/assignments/${id}/end`,{}),'Transport assignment ended')}

  async function saveMaintenance(e){e.preventDefault();const data={...maintenanceForm,odometer:maintenanceForm.odometer===''?undefined:Number(maintenanceForm.odometer),cost:Number(maintenanceForm.cost||0),nextDueDate:maintenanceForm.nextDueDate||undefined};const ok=await run(()=>api.post('/transport/maintenance',data),'Maintenance record added');if(ok)setMaintenanceForm(emptyMaintenance)}
  async function saveSettings(e){e.preventDefault();await run(()=>api.put('/transport/settings',settings),'Transport settings saved')}

  const tabs=[['dashboard','Dashboard'],['vehicles','Vehicles'],['routes','Routes & Stops'],['assignments','Assignments'],['maintenance','Maintenance'],['reports','Reports'],['settings','Settings']];
  const slice=(rows,page)=>rows.slice((page-1)*10,page*10);

  return <section className="transport-page">
    <h1>Transport</h1>
    {error&&<div className="transport-alert error">{error}</div>}{msg&&<div className="transport-alert success">{msg}</div>}
    <div className="module-top-tabs transport-tabs">{tabs.map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}</div>

    {tab==='dashboard'&&<>
      <div className="transport-stats">
        <div><b>{dashboard.totalVehicles||0}</b><span>Total Vehicles</span></div><div><b>{dashboard.activeVehicles||0}</b><span>Active Vehicles</span></div><div><b>{dashboard.activeRoutes||0}</b><span>Active Routes</span></div><div><b>{dashboard.activeAssignments||0}</b><span>Students Assigned</span></div><div><b>{dashboard.availableSeats||0}</b><span>Available Seats</span></div><div><b>{dashboard.maintenanceDue||0}</b><span>Maintenance Due</span></div><div><b>{dashboard.documentsExpiring||0}</b><span>Documents Expiring</span></div><div><b>{dashboard.documentsExpired||0}</b><span>Documents Expired</span></div>
      </div>
      <div className="transport-panel"><h3>Route Occupancy</h3><table><thead><tr><th>Route</th><th>Vehicle</th><th>Passengers</th><th>Capacity</th><th>Available</th></tr></thead><tbody>{routes.filter(r=>r.isActive).map(r=><tr key={r._id}><td>{r.code} — {r.name}</td><td>{r.vehicleId?.registrationNo||'Not assigned'}</td><td>{r.activePassengers||0}</td><td>{r.vehicleId?.seatingCapacity||0}</td><td>{r.vehicleId?.availableSeats??0}</td></tr>)}{!routes.some(r=>r.isActive)&&<tr><td colSpan="5" className="empty">No active routes.</td></tr>}</tbody></table></div>
    </>}

    {tab==='vehicles'&&<>
      {can('MANAGE_TRANSPORT_VEHICLES')&&<form className="transport-panel" onSubmit={saveVehicle}><div className="transport-heading"><h3>{vehicleEdit?'Edit Vehicle':'Add Vehicle'}</h3>{vehicleEdit&&<button type="button" className="secondary" onClick={()=>{setVehicleEdit(null);setVehicleForm(emptyVehicle)}}>Cancel</button>}</div>
        <div className="transport-grid four"><Field label="Registration No *"><input required value={vehicleForm.registrationNo} onChange={e=>setVehicleForm({...vehicleForm,registrationNo:e.target.value})}/></Field><Field label="Vehicle Type *"><select value={vehicleForm.vehicleType} onChange={e=>setVehicleForm({...vehicleForm,vehicleType:e.target.value})}><option value="bus">Bus</option><option value="coaster">Coaster</option><option value="van">Van</option><option value="car">Car</option><option value="other">Other</option></select></Field><Field label="Seating Capacity *"><input required type="number" min="1" value={vehicleForm.seatingCapacity} onChange={e=>setVehicleForm({...vehicleForm,seatingCapacity:e.target.value})}/></Field><Field label="Status"><select value={vehicleForm.status} onChange={e=>setVehicleForm({...vehicleForm,status:e.target.value})}><option value="active">Active</option><option value="maintenance">Maintenance</option><option value="inactive">Inactive</option></select></Field></div>
        <div className="transport-grid four"><Field label="Make"><input value={vehicleForm.make} onChange={e=>setVehicleForm({...vehicleForm,make:e.target.value})}/></Field><Field label="Model"><input value={vehicleForm.model} onChange={e=>setVehicleForm({...vehicleForm,model:e.target.value})}/></Field><Field label="Model Year"><input type="number" value={vehicleForm.year} onChange={e=>setVehicleForm({...vehicleForm,year:e.target.value})}/></Field><Field label="Odometer"><input type="number" min="0" value={vehicleForm.odometer} onChange={e=>setVehicleForm({...vehicleForm,odometer:e.target.value})}/></Field></div>
        <div className="transport-grid four"><Field label="Driver"><select value={vehicleForm.driverEmployeeId} onChange={e=>setVehicleForm({...vehicleForm,driverEmployeeId:e.target.value})}><option value="">Select employee</option>{employees.map(x=><option key={x._id} value={x._id}>{x.name}</option>)}</select></Field><Field label="Helper / Conductor"><select value={vehicleForm.conductorEmployeeId} onChange={e=>setVehicleForm({...vehicleForm,conductorEmployeeId:e.target.value})}><option value="">Select employee</option>{employees.map(x=><option key={x._id} value={x._id}>{x.name}</option>)}</select></Field><Field label="Insurance Expiry"><input type="date" value={vehicleForm.insuranceExpiry} onChange={e=>setVehicleForm({...vehicleForm,insuranceExpiry:e.target.value})}/></Field><Field label="Fitness Expiry"><input type="date" value={vehicleForm.fitnessExpiry} onChange={e=>setVehicleForm({...vehicleForm,fitnessExpiry:e.target.value})}/></Field></div>
        <div className="transport-grid two"><Field label="Permit / Token Expiry"><input type="date" value={vehicleForm.permitExpiry} onChange={e=>setVehicleForm({...vehicleForm,permitExpiry:e.target.value})}/></Field><Field label="Notes"><input value={vehicleForm.notes} onChange={e=>setVehicleForm({...vehicleForm,notes:e.target.value})}/></Field></div><button disabled={busy}>{vehicleEdit?'Update Vehicle':'Add Vehicle'}</button>
      </form>}
      <div className="transport-panel"><h3>Vehicles</h3><table><thead><tr><th>Code</th><th>Registration</th><th>Type</th><th>Capacity</th><th>Occupied</th><th>Available</th><th>Driver</th><th>Status</th><th>Action</th></tr></thead><tbody>{slice(vehicles,vehiclePage).map(v=><tr key={v._id}><td>{v.vehicleCode}</td><td>{v.registrationNo}</td><td>{v.vehicleType}</td><td>{v.seatingCapacity}</td><td>{v.occupiedSeats||0}</td><td>{v.availableSeats||0}</td><td>{v.driverEmployeeId?.name||'—'}</td><td><span className={`transport-badge ${v.status}`}>{v.status}</span></td><td>{can('MANAGE_TRANSPORT_VEHICLES')&&<button className="small" onClick={()=>editVehicle(v)}>Edit</button>}</td></tr>)}{!vehicles.length&&<tr><td colSpan="9" className="empty">No vehicles found.</td></tr>}</tbody></table><Pager page={vehiclePage} setPage={setVehiclePage} total={vehicles.length}/></div>
    </>}

    {tab==='routes'&&<>
      {can('MANAGE_TRANSPORT_ROUTES')&&<form className="transport-panel" onSubmit={saveRoute}><div className="transport-heading"><h3>{routeEdit?'Edit Route':'Add Route'}</h3>{routeEdit&&<button type="button" className="secondary" onClick={()=>{setRouteEdit(null);setRouteForm(emptyRoute)}}>Cancel</button>}</div>
        <div className="transport-grid four"><Field label="Route Name *"><input required value={routeForm.name} onChange={e=>setRouteForm({...routeForm,name:e.target.value})}/></Field><Field label="Start Point"><input value={routeForm.startPoint} onChange={e=>setRouteForm({...routeForm,startPoint:e.target.value})}/></Field><Field label="End Point"><input value={routeForm.endPoint} onChange={e=>setRouteForm({...routeForm,endPoint:e.target.value})}/></Field><Field label="Vehicle"><select value={routeForm.vehicleId} onChange={e=>setRouteForm({...routeForm,vehicleId:e.target.value})}><option value="">Select vehicle</option>{vehicles.filter(v=>v.status==='active'||v._id===routeForm.vehicleId).map(v=><option key={v._id} value={v._id}>{v.vehicleCode} — {v.registrationNo} ({v.availableSeats} seats available)</option>)}</select></Field></div>
        <div className="transport-grid two"><Field label="Default Monthly Fee"><input type="number" min="0" value={routeForm.defaultMonthlyFee} onChange={e=>setRouteForm({...routeForm,defaultMonthlyFee:e.target.value})}/></Field><Field label="Status"><select value={routeForm.isActive?'active':'inactive'} onChange={e=>setRouteForm({...routeForm,isActive:e.target.value==='active'})}><option value="active">Active</option><option value="inactive">Inactive</option></select></Field></div>
        <div className="transport-subhead"><b>Stops</b><button type="button" className="secondary small" onClick={addStop}>+ Add Stop</button></div>
        {routeForm.stops.map((s,i)=><div className="transport-stop-row" key={i}><span className="stop-no">{i+1}</span><input required placeholder="Stop name" value={s.name} onChange={e=>updateStop(i,'name',e.target.value)}/><input type="time" title="Pickup time" value={s.pickupTime} onChange={e=>updateStop(i,'pickupTime',e.target.value)}/><input type="time" title="Drop time" value={s.dropTime} onChange={e=>updateStop(i,'dropTime',e.target.value)}/><input type="number" min="0" placeholder="Monthly fee" value={s.monthlyFee} onChange={e=>updateStop(i,'monthlyFee',e.target.value)}/><input placeholder="Landmark" value={s.landmark} onChange={e=>updateStop(i,'landmark',e.target.value)}/><button type="button" className="danger small" disabled={routeForm.stops.length===1} onClick={()=>removeStop(i)}>Remove</button></div>)}
        <button disabled={busy}>{routeEdit?'Update Route':'Add Route'}</button>
      </form>}
      <div className="transport-panel"><h3>Routes & Stops</h3><table><thead><tr><th>Code</th><th>Route</th><th>Vehicle</th><th>Stops</th><th>Passengers</th><th>Capacity</th><th>Status</th><th>Action</th></tr></thead><tbody>{slice(routes,routePage).map(r=><tr key={r._id}><td>{r.code}</td><td>{r.name}</td><td>{r.vehicleId?.registrationNo||'—'}</td><td>{r.stops?.length||0}</td><td>{r.activePassengers||0}</td><td>{r.vehicleId?.seatingCapacity||0}</td><td><span className={`transport-badge ${r.isActive?'active':'inactive'}`}>{r.isActive?'Active':'Inactive'}</span></td><td>{can('MANAGE_TRANSPORT_ROUTES')&&<button className="small" onClick={()=>editRoute(r)}>Edit</button>}</td></tr>)}{!routes.length&&<tr><td colSpan="8" className="empty">No routes found.</td></tr>}</tbody></table><Pager page={routePage} setPage={setRoutePage} total={routes.length}/></div>
    </>}

    {tab==='assignments'&&<>
      {can('MANAGE_TRANSPORT_ASSIGNMENTS')&&<form className="transport-panel" onSubmit={saveAssignment}><h3>Assign Student</h3>
        <div className="transport-grid three"><Field label="Session *"><select required value={assignmentForm.academicSessionId} onChange={e=>{setAssignmentForm({...assignmentForm,academicSessionId:e.target.value,studentId:''});setStudentSearch('')}}><option value="">Select session</option>{(lookups.sessions||[]).map(x=><option key={x._id} value={x._id}>{x.name}</option>)}</select></Field><Field label="Program / Class *"><select required value={assignmentForm.programId} onChange={e=>{setAssignmentForm({...assignmentForm,programId:e.target.value,studentId:''});setStudentSearch('')}}><option value="">Select program/class</option>{(lookups.programs||[]).map(x=><option key={x._id} value={x._id}>{x.name}</option>)}</select></Field><Field label="Student *"><input required list="transport-students" disabled={!assignmentForm.academicSessionId||!assignmentForm.programId} placeholder="Type name, roll no or form no" value={studentSearch} onChange={e=>onStudentInput(e.target.value)}/><datalist id="transport-students">{studentOptions.map(x=><option key={x.id} value={x.label}/>)}</datalist></Field></div>
        <div className="transport-grid three"><Field label="Route *"><select required value={assignmentForm.routeId} onChange={e=>onRouteChange(e.target.value)}><option value="">Select route</option>{activeRoutes.map(r=><option key={r._id} value={r._id}>{r.code} — {r.name}{settings.enforceCapacity?` (${r.vehicleId?.availableSeats??0} vehicle seats available)`:''}</option>)}</select></Field><Field label="Stop *"><select required disabled={!selectedRoute} value={assignmentForm.stopId} onChange={e=>onStopChange(e.target.value)}><option value="">Select stop</option>{(selectedRoute?.stops||[]).map(s=><option key={s._id} value={s._id}>{s.name}</option>)}</select></Field><Field label="Vehicle"><input readOnly value={selectedRoute?.vehicleId?`${selectedRoute.vehicleId.vehicleCode} — ${selectedRoute.vehicleId.registrationNo}`:''} placeholder="Assigned from route"/></Field></div>
        <div className="transport-grid three"><Field label="Start Date *"><input required type="date" value={assignmentForm.startDate} onChange={e=>setAssignmentForm({...assignmentForm,startDate:e.target.value})}/></Field><Field label="End Date"><input type="date" min={assignmentForm.startDate||undefined} value={assignmentForm.endDate} onChange={e=>setAssignmentForm({...assignmentForm,endDate:e.target.value})}/></Field><Field label="Status"><select value={assignmentForm.status} onChange={e=>setAssignmentForm({...assignmentForm,status:e.target.value})}><option value="active">Active</option><option value="paused">Paused</option></select></Field></div>
        <div className="transport-grid three"><Field label="Monthly Fee"><input type="number" min="0" readOnly={!settings.allowFeeOverride} value={assignmentForm.monthlyFee} onChange={e=>setAssignmentForm({...assignmentForm,monthlyFee:e.target.value})}/></Field><Field label="Travel Type"><select value={assignmentForm.pickupType} onChange={e=>setAssignmentForm({...assignmentForm,pickupType:e.target.value})}><option value="both">Both Ways</option><option value="pickup">Pickup Only</option><option value="drop">Drop Only</option></select></Field><Field label="Notes"><input value={assignmentForm.notes} onChange={e=>setAssignmentForm({...assignmentForm,notes:e.target.value})}/></Field></div><button disabled={busy}>Assign Student</button>
      </form>}
      <div className="transport-panel"><h3>Transport Assignments</h3><table><thead><tr><th>Student</th><th>Roll/Form</th><th>Session</th><th>Route</th><th>Stop</th><th>Vehicle</th><th>Fee</th><th>Status</th><th>Action</th></tr></thead><tbody>{slice(assignments,assignmentPage).map(a=>{const stop=a.routeId?.stops?.find(s=>String(s._id)===String(a.stopId));return <tr key={a._id}><td>{a.studentId?.name||'—'}</td><td>{a.studentId?.rollNo||a.studentId?.registrationNo||a.studentId?.admissionNo||'—'}</td><td>{a.academicSessionId?.name||'—'}</td><td>{a.routeId?.name||'—'}</td><td>{stop?.name||'—'}</td><td>{a.routeId?.vehicleId?.registrationNo||'—'}</td><td>{money(a.monthlyFee)}</td><td><span className={`transport-badge ${a.status}`}>{a.status}</span></td><td>{['active','paused'].includes(a.status)&&can('MANAGE_TRANSPORT_ASSIGNMENTS')&&<button className="danger small" onClick={()=>endAssignment(a._id)}>End</button>}</td></tr>})}{!assignments.length&&<tr><td colSpan="9" className="empty">No transport assignments found.</td></tr>}</tbody></table><Pager page={assignmentPage} setPage={setAssignmentPage} total={assignments.length}/></div>
    </>}

    {tab==='maintenance'&&<>
      {can('MANAGE_TRANSPORT_MAINTENANCE')&&<form className="transport-panel" onSubmit={saveMaintenance}><h3>Add Maintenance</h3><div className="transport-grid four"><Field label="Vehicle *"><select required value={maintenanceForm.vehicleId} onChange={e=>setMaintenanceForm({...maintenanceForm,vehicleId:e.target.value})}><option value="">Select vehicle</option>{vehicles.map(v=><option key={v._id} value={v._id}>{v.vehicleCode} — {v.registrationNo}</option>)}</select></Field><Field label="Type *"><select value={maintenanceForm.type} onChange={e=>setMaintenanceForm({...maintenanceForm,type:e.target.value})}><option value="service">Service</option><option value="repair">Repair</option><option value="tyre">Tyre</option><option value="oil">Oil Change</option><option value="inspection">Inspection</option><option value="other">Other</option></select></Field><Field label="Service Date *"><input required type="date" value={maintenanceForm.serviceDate} onChange={e=>setMaintenanceForm({...maintenanceForm,serviceDate:e.target.value})}/></Field><Field label="Status"><select value={maintenanceForm.status} onChange={e=>setMaintenanceForm({...maintenanceForm,status:e.target.value})}><option value="scheduled">Scheduled</option><option value="in_progress">In Progress</option><option value="completed">Completed</option></select></Field></div><div className="transport-grid four"><Field label="Odometer"><input type="number" min="0" value={maintenanceForm.odometer} onChange={e=>setMaintenanceForm({...maintenanceForm,odometer:e.target.value})}/></Field><Field label="Cost"><input type="number" min="0" value={maintenanceForm.cost} onChange={e=>setMaintenanceForm({...maintenanceForm,cost:e.target.value})}/></Field><Field label="Vendor / Workshop"><input value={maintenanceForm.vendor} onChange={e=>setMaintenanceForm({...maintenanceForm,vendor:e.target.value})}/></Field><Field label="Next Due Date"><input type="date" min={maintenanceForm.serviceDate||undefined} value={maintenanceForm.nextDueDate} onChange={e=>setMaintenanceForm({...maintenanceForm,nextDueDate:e.target.value})}/></Field></div><Field label="Description"><input value={maintenanceForm.description} onChange={e=>setMaintenanceForm({...maintenanceForm,description:e.target.value})}/></Field><button disabled={busy}>Save Maintenance</button></form>}
      <div className="transport-panel"><h3>Maintenance History</h3><table><thead><tr><th>Date</th><th>Vehicle</th><th>Type</th><th>Odometer</th><th>Vendor</th><th>Cost</th><th>Next Due</th><th>Status</th></tr></thead><tbody>{slice(maintenance,maintenancePage).map(m=><tr key={m._id}><td>{m.serviceDate?.slice(0,10)}</td><td>{m.vehicleId?.registrationNo||'—'}</td><td>{m.type}</td><td>{m.odometer??'—'}</td><td>{m.vendor||'—'}</td><td>{money(m.cost)}</td><td>{m.nextDueDate?.slice(0,10)||'—'}</td><td><span className={`transport-badge ${m.status}`}>{m.status}</span></td></tr>)}{!maintenance.length&&<tr><td colSpan="8" className="empty">No maintenance records.</td></tr>}</tbody></table><Pager page={maintenancePage} setPage={setMaintenancePage} total={maintenance.length}/></div>
    </>}

    {tab==='reports'&&<section className="transport-panel cms-report-workspace"><div className="transport-heading cms-report-head"><div><h3>Transport Reports</h3><p>Route utilization, passenger assignments, seating capacity and monthly assigned fees.</p></div><button type="button" onClick={()=>window.print()}>Print Report</button></div><div className="transport-report-cards cms-report-kpis"><div className="cms-report-kpi"><span>Active Students</span><b>{assignments.filter(a=>a.status==='active').length}</b></div><div className="cms-report-kpi"><span>Active Routes</span><b>{routes.filter(r=>r.isActive).length}</b></div><div className="cms-report-kpi"><span>Total Capacity</span><b>{vehicles.reduce((s,v)=>s+Number(v.seatingCapacity||0),0)}</b></div><div className="cms-report-kpi"><span>Monthly Assigned Fees</span><b>PKR {money(assignments.filter(a=>a.status==='active').reduce((s,a)=>s+Number(a.monthlyFee||0),0))}</b></div></div><div className="cms-report-table-card"><div className="cms-report-table-title"><div><h4>Route Capacity Statement</h4><p>Passengers and available seats by route.</p></div></div><div className="cms-report-table-wrap"><table><thead><tr><th>Route</th><th>Vehicle</th><th>Stops</th><th>Passengers</th><th>Capacity</th><th>Available</th></tr></thead><tbody>{routes.map(r=><tr key={r._id}><td>{r.code} — {r.name}</td><td>{r.vehicleId?.registrationNo||'—'}</td><td>{r.stops?.length||0}</td><td>{r.activePassengers||0}</td><td>{r.vehicleId?.seatingCapacity||0}</td><td>{Math.max(0,(r.vehicleId?.seatingCapacity||0)-(r.activePassengers||0))}</td></tr>)}{!routes.length&&<tr><td colSpan="6" className="cms-report-empty">No route records found.</td></tr>}</tbody></table></div></div></section>}

    {tab==='settings'&&<form className="transport-panel" onSubmit={saveSettings}><h3>Transport Settings</h3><div className="transport-settings-grid"><label><input type="checkbox" checked={!!settings.enforceCapacity} onChange={e=>setSettings({...settings,enforceCapacity:e.target.checked})}/><span><b>Enforce Seat Capacity</b><small>Prevent assignments when the route vehicle is full.</small></span></label><label><input type="checkbox" checked={!!settings.allowRouteChange} onChange={e=>setSettings({...settings,allowRouteChange:e.target.checked})}/><span><b>Allow Route Change</b><small>Close the previous assignment when a student changes route.</small></span></label><label><input type="checkbox" checked={!!settings.allowFeeOverride} onChange={e=>setSettings({...settings,allowFeeOverride:e.target.checked})}/><span><b>Allow Fee Override</b><small>Allow a student's monthly fee to differ from the selected stop.</small></span></label></div><div className="transport-grid two"><Field label="Maintenance Reminder Days"><input type="number" min="0" value={settings.maintenanceReminderDays??30} onChange={e=>setSettings({...settings,maintenanceReminderDays:Number(e.target.value)})}/></Field><Field label="Document Expiry Reminder Days"><input type="number" min="0" value={settings.documentExpiryReminderDays??30} onChange={e=>setSettings({...settings,documentExpiryReminderDays:Number(e.target.value)})}/></Field></div>{can('MANAGE_TRANSPORT')&&<button disabled={busy}>Save Settings</button>}</form>}
  </section>;
}
