import {useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'react-router-dom';
import api from '../../api/client';
import {useAuth} from '../../contexts/AuthContext';
import './events.css';

const pad=n=>String(n).padStart(2,'0');
const dateOnly=v=>v?String(v).slice(0,10):'';
const timeOnly=v=>{if(!v)return'';const d=new Date(v);return `${pad(d.getHours())}:${pad(d.getMinutes())}`};
const fmtDate=v=>v?new Date(v).toLocaleDateString():'-';
const fmtDateTime=v=>v?new Date(v).toLocaleString():'-';
const label=v=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const errText=e=>e?.response?.data?.error||e?.response?.data?.message||e?.message||'Request failed';
const nowLocal=()=>{const d=new Date();return {date:`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,time:`${pad(d.getHours())}:${pad(d.getMinutes())}`}};
const blank=()=>{const n=nowLocal();return {title:'',category:'academic',startDate:n.date,endDate:n.date,startTime:'09:00',endTime:'11:00',venue:'',audienceType:'all',branchId:'',academicSessionId:'',targetProgramIds:[],targetSectionIds:[],employeeCategory:'',description:'',organizerEmployeeId:'',priority:'normal',status:'draft',registrationRequired:false,capacity:''}};
const toIso=(date,time)=>date?new Date(`${date}T${time||'00:00'}`).toISOString():null;

export default function EventsPage(){
  const {user}=useAuth();
  const [searchParams,setSearchParams]=useSearchParams();
  const [tab,setTabState]=useState(searchParams.get('tab')||'dashboard');
  const [meta,setMeta]=useState({sessions:[],programs:[],sections:[],branches:[],employees:[],settings:{}});
  const [dashboard,setDashboard]=useState({}),[events,setEvents]=useState([]),[settings,setSettings]=useState({});
  const [form,setForm]=useState(blank()),[editing,setEditing]=useState(''),[showForm,setShowForm]=useState(false);
  const [filters,setFilters]=useState({status:'',category:'',audienceType:'',from:'',to:'',search:''});
  const [calendarDate,setCalendarDate]=useState(new Date());
  const [msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
  const perms=new Set(user?.permissions||user?.effectivePermissions||[]);const can=p=>user?.systemRole==='platform_owner'||perms.has('*')||perms.has(p);
  const setTab=next=>{setTabState(next);setSearchParams(prev=>{const x=new URLSearchParams(prev);x.set('tab',next);return x;});};
  useEffect(()=>{const next=searchParams.get('tab')||'dashboard';if(next!==tab)setTabState(next)},[searchParams]);

  const filteredPrograms=useMemo(()=>meta.programs.filter(p=>!form.branchId||String(p.branchId?._id||p.branchId||'')===String(form.branchId)),[meta.programs,form.branchId]);
  const filteredSections=useMemo(()=>meta.sections.filter(s=>!form.targetProgramIds.length||form.targetProgramIds.includes(String(s.programId?._id||s.programId||''))),[meta.sections,form.targetProgramIds]);
  const displayEvents=useMemo(()=>events.filter(e=>{const q=filters.search.trim().toLowerCase();return !q||`${e.eventNo||e.code||''} ${e.title||''} ${e.venue||''} ${e.description||''}`.toLowerCase().includes(q)}),[events,filters.search]);

  async function loadMeta(){const {data}=await api.get('/events/meta');setMeta(data||{});setSettings(data?.settings||{})}
  async function load(){try{setMsg('');await loadMeta();const d=await api.get('/events/dashboard');setDashboard(d.data||{});const p=new URLSearchParams();['status','category','audienceType','from','to'].forEach(k=>filters[k]&&p.set(k,filters[k]));const r=await api.get(`/events${p.toString()?`?${p}`:''}`);setEvents(r.data||[])}catch(e){setMsg(errText(e))}}
  useEffect(()=>{load()},[filters.status,filters.category,filters.audienceType,filters.from,filters.to]);

  function openNew(){setEditing('');setForm(blank());setShowForm(true)}
  function openEdit(e){setEditing(e._id);setForm({title:e.title||'',category:e.category||'other',startDate:dateOnly(e.startAt),endDate:dateOnly(e.endAt),startTime:timeOnly(e.startAt),endTime:timeOnly(e.endAt),venue:e.venue||'',audienceType:e.audienceType||'all',branchId:e.branchId?._id||'',academicSessionId:e.academicSessionId?._id||'',targetProgramIds:(e.targetProgramIds||[]).map(x=>String(x._id||x)),targetSectionIds:(e.targetSectionIds||[]).map(x=>String(x._id||x)),employeeCategory:e.employeeCategory||'',description:e.description||'',organizerEmployeeId:e.organizerEmployeeId?._id||'',priority:e.priority||'normal',status:['draft','scheduled'].includes(e.status)?e.status:'draft',registrationRequired:Boolean(e.registrationRequired),capacity:e.capacity||''});setShowForm(true)}
  async function saveEvent(ev){ev.preventDefault();setBusy(true);setMsg('');try{const payload={title:form.title,category:form.category,startAt:toIso(form.startDate,form.startTime),endAt:toIso(form.endDate||form.startDate,form.endTime),venue:form.venue,audienceType:form.audienceType,branchId:form.branchId||null,academicSessionId:form.academicSessionId||null,targetProgramIds:form.audienceType==='program'?form.targetProgramIds:[],targetSectionIds:form.audienceType==='section'?form.targetSectionIds:[],employeeCategory:form.audienceType==='employee_category'?form.employeeCategory:undefined,description:form.description,organizerEmployeeId:form.organizerEmployeeId||null,priority:form.priority,status:form.status,registrationRequired:form.registrationRequired,capacity:form.registrationRequired?Number(form.capacity||0):0};if(editing)await api.put(`/events/${editing}`,payload);else await api.post('/events',payload);setShowForm(false);setEditing('');setForm(blank());setMsg(editing?'Event updated.':'Event created.');await load()}catch(e){setMsg(errText(e))}finally{setBusy(false)}}
  async function publish(id){setBusy(true);try{const {data}=await api.post(`/events/${id}/publish`);setMsg(`Event ${label(data?.status||'published')}.`);await load()}catch(e){setMsg(errText(e))}finally{setBusy(false)}}
  async function cancel(id){if(!confirm('Cancel this event?'))return;setBusy(true);try{await api.post(`/events/${id}/cancel`);setMsg('Event cancelled.');await load()}catch(e){setMsg(errText(e))}finally{setBusy(false)}}
  async function uploadAttachment(id,file){if(!file)return;setBusy(true);try{const fd=new FormData();fd.append('attachment',file);await api.post(`/events/${id}/attachment`,fd,{headers:{'Content-Type':'multipart/form-data'}});setMsg('Attachment uploaded.');await load()}catch(e){setMsg(errText(e))}finally{setBusy(false)}}
  async function register(id){setBusy(true);try{await api.post(`/events/${id}/register`);setMsg('Registered for event.')}catch(e){setMsg(errText(e))}finally{setBusy(false)}}
  async function saveSettings(ev){ev.preventDefault();setBusy(true);try{const {data}=await api.put('/events/settings',settings);setSettings(data||{});setMsg('Event settings saved.')}catch(e){setMsg(errText(e))}finally{setBusy(false)}}

  const monthEvents=useMemo(()=>events.filter(e=>{const d=new Date(e.startAt);return d.getFullYear()===calendarDate.getFullYear()&&d.getMonth()===calendarDate.getMonth()}),[events,calendarDate]);
  const calendarCells=useMemo(()=>{const y=calendarDate.getFullYear(),m=calendarDate.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate();const cells=[];for(let i=0;i<first;i++)cells.push(null);for(let d=1;d<=days;d++)cells.push(d);while(cells.length%7)cells.push(null);return cells},[calendarDate]);

  return <section className="events-page">
    <div className="events-heading"><div><h1>Events</h1><p>Manage institutional activities, schedules and audience visibility.</p></div>{can('MANAGE_EVENTS')&&tab==='events'&&<button onClick={openNew}>+ Add Event</button>}</div>
    <div className="events-tabs">{[['dashboard','Dashboard'],['events','Events'],['calendar','Calendar'],['reports','Reports'],['settings','Settings']].map(([k,t])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{t}</button>)}</div>
    {msg&&<div className="events-message">{msg}</div>}

    {tab==='dashboard'&&<>
      <div className="events-stat-grid">
        <div className="event-stat"><span>Total Events</span><strong>{dashboard.total||0}</strong></div><div className="event-stat"><span>Upcoming</span><strong>{dashboard.upcoming||0}</strong></div><div className="event-stat"><span>Today</span><strong>{dashboard.today||0}</strong></div><div className="event-stat"><span>Completed</span><strong>{dashboard.completed||0}</strong></div><div className="event-stat"><span>Cancelled</span><strong>{dashboard.cancelled||0}</strong></div>
      </div>
      <div className="events-panel"><h3>Next Upcoming Events</h3><EventTable rows={dashboard.next||[]} compact canManage={false} onRegister={register}/></div>
    </>}

    {tab==='events'&&<>
      <div className="events-toolbar"><input placeholder="Search Event No, title, venue..." value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/><select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">All Statuses</option>{['draft','scheduled','active','completed','cancelled'].map(x=><option key={x} value={x}>{label(x)}</option>)}</select><select value={filters.category} onChange={e=>setFilters({...filters,category:e.target.value})}><option value="">All Types</option>{['academic','cultural','sports','seminar','workshop','orientation','social','other'].map(x=><option key={x} value={x}>{label(x)}</option>)}</select><select value={filters.audienceType} onChange={e=>setFilters({...filters,audienceType:e.target.value})}><option value="">All Audiences</option>{['all','students','employees','program','section','employee_category'].map(x=><option key={x} value={x}>{label(x)}</option>)}</select></div>
      {showForm&&<form className="events-form" onSubmit={saveEvent}>
        <div className="events-form-title"><h3>{editing?'Edit Event':'Create Event'}</h3><button type="button" className="events-close" onClick={()=>setShowForm(false)}>×</button></div>
        <div className="events-form-grid four"><Field label="Event Title *"><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><Field label="Event Type *"><select required value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{['academic','cultural','sports','seminar','workshop','orientation','social','other'].map(x=><option key={x} value={x}>{label(x)}</option>)}</select></Field><Field label="Priority"><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}>{['normal','important','urgent'].map(x=><option key={x} value={x}>{label(x)}</option>)}</select></Field><Field label="Status"><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="draft">Draft</option><option value="scheduled">Scheduled</option></select></Field></div>
        <div className="events-form-grid four"><Field label="Start Date *"><input type="date" required value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value,endDate:form.endDate||e.target.value})}/></Field><Field label="Start Time"><input type="time" value={form.startTime} onChange={e=>setForm({...form,startTime:e.target.value})}/></Field><Field label="End Date"><input type="date" value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})}/></Field><Field label="End Time"><input type="time" value={form.endTime} onChange={e=>setForm({...form,endTime:e.target.value})}/></Field></div>
        <div className="events-form-grid four"><Field label="Venue"><input value={form.venue} onChange={e=>setForm({...form,venue:e.target.value})}/></Field><Field label="Audience *"><select value={form.audienceType} onChange={e=>setForm({...form,audienceType:e.target.value,targetProgramIds:[],targetSectionIds:[]})}>{[['all','All'],['students','Students'],['employees','Employees'],['program','Specific Program/Class'],['section','Specific Section'],['employee_category','Specific Employee Category']].map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></Field><Field label="Branch"><select value={form.branchId} onChange={e=>setForm({...form,branchId:e.target.value})}><option value="">All Branches</option>{meta.branches.map(x=><option key={x._id} value={x._id}>{x.name}</option>)}</select></Field><Field label="Organizer"><select value={form.organizerEmployeeId} onChange={e=>setForm({...form,organizerEmployeeId:e.target.value})}><option value="">Not Assigned</option>{meta.employees.map(x=><option key={x._id} value={x._id}>{x.employeeNo||x.employeeCode} - {x.name}</option>)}</select></Field></div>
        {(form.audienceType==='program'||form.audienceType==='section')&&<div className="events-form-grid three"><Field label="Session"><select value={form.academicSessionId} onChange={e=>setForm({...form,academicSessionId:e.target.value})}><option value="">All Sessions</option>{meta.sessions.map(x=><option key={x._id} value={x._id}>{x.name||x.sessionName||x.label}</option>)}</select></Field>{form.audienceType==='program'&&<Field label="Program / Class *"><select multiple value={form.targetProgramIds} onChange={e=>setForm({...form,targetProgramIds:Array.from(e.target.selectedOptions,x=>x.value)})}>{filteredPrograms.map(x=><option key={x._id} value={x._id}>{x.name}</option>)}</select></Field>}{form.audienceType==='section'&&<><Field label="Program / Class"><select multiple value={form.targetProgramIds} onChange={e=>setForm({...form,targetProgramIds:Array.from(e.target.selectedOptions,x=>x.value),targetSectionIds:[]})}>{filteredPrograms.map(x=><option key={x._id} value={x._id}>{x.name}</option>)}</select></Field><Field label="Section *"><select multiple value={form.targetSectionIds} onChange={e=>setForm({...form,targetSectionIds:Array.from(e.target.selectedOptions,x=>x.value)})}>{filteredSections.map(x=><option key={x._id} value={x._id}>{x.name||x.sectionName||x.code}</option>)}</select></Field></>}</div>}
        {form.audienceType==='employee_category'&&<div className="events-form-grid three"><Field label="Employee Category *"><select value={form.employeeCategory} onChange={e=>setForm({...form,employeeCategory:e.target.value})}><option value="">Select Category</option><option value="academic_staff">Academic Staff</option><option value="non_teaching_staff">Non-Teaching Staff</option></select></Field></div>}
        <div className="events-form-grid two"><Field label="Description"><textarea rows="3" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><div className="events-checks"><label><input type="checkbox" checked={form.registrationRequired} onChange={e=>setForm({...form,registrationRequired:e.target.checked})}/> Registration Required</label>{form.registrationRequired&&<Field label="Capacity (0 = unlimited)"><input type="number" min="0" value={form.capacity} onChange={e=>setForm({...form,capacity:e.target.value})}/></Field>}</div></div>
        <div className="events-form-actions"><button type="button" className="secondary" onClick={()=>setShowForm(false)}>Cancel</button><button disabled={busy}>{busy?'Saving...':'Save Event'}</button></div>
      </form>}
      <EventTable rows={displayEvents} canManage={can('MANAGE_EVENTS')} onEdit={openEdit} onPublish={publish} onCancel={cancel} onUpload={uploadAttachment} onRegister={register} allowAttachments={settings.allowAttachments!==false}/>
    </>}

    {tab==='calendar'&&<div className="events-panel">
      <div className="calendar-head"><button className="secondary" onClick={()=>setCalendarDate(new Date(calendarDate.getFullYear(),calendarDate.getMonth()-1,1))}>‹</button><h3>{calendarDate.toLocaleString(undefined,{month:'long',year:'numeric'})}</h3><button className="secondary" onClick={()=>setCalendarDate(new Date(calendarDate.getFullYear(),calendarDate.getMonth()+1,1))}>›</button></div>
      <div className="calendar-grid calendar-week">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=><strong key={x}>{x}</strong>)}</div>
      <div className="calendar-grid">{calendarCells.map((d,i)=><div key={i} className={`calendar-cell${!d?' empty':''}`}>{d&&<><span className="calendar-day">{d}</span>{monthEvents.filter(e=>new Date(e.startAt).getDate()===d).slice(0,3).map(e=><button key={e._id} className={`calendar-event ${e.status}`} onClick={()=>{if(can('MANAGE_EVENTS')){openEdit(e);setTab('events')}}}>{e.title}</button>)}</>}</div>)}</div>
    </div>}

    {tab==='reports'&&<section className="events-panel cms-report-workspace"><div className="events-report-head cms-report-head"><div><h3>Event Register</h3><p>Event activity and schedule register for the selected date range.</p></div><button className="secondary" onClick={()=>window.print()}>Print Report</button></div><div className="events-toolbar compact cms-report-filterbar"><label><span>From</span><input type="date" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/></label><label><span>To</span><input type="date" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/></label></div><div className="cms-report-kpis"><div className="cms-report-kpi"><span>Report Records</span><strong>{displayEvents.length}</strong><small>Events matching current filters</small></div></div><div className="cms-report-table-card cms-report-table-wrap"><EventTable rows={displayEvents} canManage={false}/></div></section>}

    {tab==='settings'&&<form className="events-panel events-settings" onSubmit={saveSettings}><h3>Event Settings</h3><div className="settings-grid"><SettingCheck label="Events Module Enabled" checked={settings.enabled!==false} onChange={v=>setSettings({...settings,enabled:v})}/><SettingCheck label="Allow Attachments" checked={settings.allowAttachments!==false} onChange={v=>setSettings({...settings,allowAttachments:v})}/><SettingCheck label="Allow Scheduled Events" checked={settings.allowScheduledEvents!==false} onChange={v=>setSettings({...settings,allowScheduledEvents:v})}/><SettingCheck label="Require Approval Before Publishing" checked={Boolean(settings.requireApprovalBeforePublishing)} onChange={v=>setSettings({...settings,requireApprovalBeforePublishing:v})}/><SettingCheck label="Show Events on Dashboard" checked={settings.showEventsOnDashboard!==false} onChange={v=>setSettings({...settings,showEventsOnDashboard:v})}/><Field label="Default Event Duration (Hours)"><input type="number" min="0.25" step="0.25" value={settings.defaultDurationHours??2} onChange={e=>setSettings({...settings,defaultDurationHours:Number(e.target.value)})}/></Field></div>{can('MANAGE_EVENTS')&&<div className="events-form-actions"><button disabled={busy}>Save Settings</button></div>}</form>}
  </section>;
}

function Field({label,children}){return <label className="event-field"><span>{label}</span>{children}</label>}
function SettingCheck({label,checked,onChange}){return <label className="setting-check"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><span>{label}</span></label>}
function EventTable({rows=[],canManage,onEdit,onPublish,onCancel,onUpload,onRegister,allowAttachments=true,compact=false}){return <div className="events-table-wrap"><table className="events-table"><thead><tr><th>Event No</th><th>Title</th><th>Type</th><th>Date / Time</th><th>Venue</th><th>Audience</th><th>Status</th>{!compact&&<th>Actions</th>}</tr></thead><tbody>{rows.length?rows.map(e=><tr key={e._id}><td>{e.eventNo||e.code||'-'}</td><td><strong>{e.title}</strong>{e.priority&&e.priority!=='normal'&&<span className={`priority ${e.priority}`}>{label(e.priority)}</span>}</td><td>{label(e.category)}</td><td>{fmtDateTime(e.startAt)}{e.endAt&&<small> to {fmtDateTime(e.endAt)}</small>}</td><td>{e.venue||'-'}</td><td>{label(e.audienceType||'all')}</td><td><span className={`event-status ${e.status}`}>{label(e.status==='published'?'active':e.status)}</span></td>{!compact&&<td><div className="event-actions">{canManage&&onEdit&&!['completed','cancelled'].includes(e.status)&&<button className="secondary" onClick={()=>onEdit(e)}>Edit</button>}{canManage&&onPublish&&['draft','scheduled'].includes(e.status)&&<button onClick={()=>onPublish(e._id)}>Publish</button>}{canManage&&onCancel&&!['completed','cancelled'].includes(e.status)&&<button className="danger" onClick={()=>onCancel(e._id)}>Cancel</button>}{canManage&&allowAttachments&&onUpload&&<label className="file-action">Attach<input type="file" hidden accept=".pdf,.jpg,.jpeg,.png,.webp,.doc,.docx" onChange={x=>onUpload(e._id,x.target.files?.[0])}/></label>}{e.attachmentUrl&&<a className="file-action" href={e.attachmentUrl} target="_blank" rel="noreferrer">Open File</a>}{!canManage&&e.registrationRequired&&onRegister&&<button onClick={()=>onRegister(e._id)}>Register</button>}</div></td>}</tr>):<tr><td colSpan={compact?7:8} className="empty-row">No events found.</td></tr>}</tbody></table></div>}
