const { cleanIds } = require('../../utils/normalize');
const { collegeIdFromRequest: cid, sendError: bad } = require('../../utils/request');
const pushNotifications=require('../../services/pushNotificationService');
const Event=require('../../models/Event');
const EventRegistration=require('../../models/EventRegistration');
const EventSettings=require('../../models/EventSettings');
const Student=require('../../models/Student');
const Employee=require('../../models/Employee');
const AcademicSession=require('../../models/AcademicSession');
const Program=require('../../models/Program');
const Section=require('../../models/Section');
const Branch=require('../../models/Branch');
const Sequence=require('../../models/Sequence');
const {audit}=require('../../services/auditService');

function has(user,p){const perms=new Set(user?.permissions||user?.effectivePermissions||user?.directPermissions||[]);return user?.systemRole==='platform_owner'||perms.has('*')||perms.has(p)}
function ownParticipant(user){if(user?.linkedStudentId)return {participantType:'student',studentId:user.linkedStudentId};if(user?.linkedEmployeeId)return {participantType:'employee',employeeId:user.linkedEmployeeId};return null}
function safeDate(v){if(!v)return null;const d=new Date(v);return Number.isNaN(d.getTime())?null:d}

async function getSettings(collegeId){return EventSettings.findOneAndUpdate({collegeId},{$setOnInsert:{collegeId}},{new:true,upsert:true,setDefaultsOnInsert:true})}
async function nextEventNo(collegeId){const yy=String(new Date().getFullYear()).slice(-2);const seq=await Sequence.findOneAndUpdate({collegeId,key:`event-${yy}`},{$inc:{value:1},$setOnInsert:{collegeId,key:`event-${yy}`}},{new:true,upsert:true,setDefaultsOnInsert:true});return `EVT-${yy}${String(seq.value).padStart(4,'0')}`}
async function refreshStatuses(collegeId){const now=new Date();await Event.updateMany({collegeId,status:'scheduled',startAt:{$lte:now},endAt:{$gte:now}},{$set:{status:'active'}});await Event.updateMany({collegeId,status:{$in:['scheduled','active','published']},endAt:{$lt:now}},{$set:{status:'completed'}})}
function populate(q){return q.populate('branchId','name code').populate('academicSessionId','name sessionName label').populate('targetProgramIds','name code').populate('targetSectionIds','name sectionName code').populate('organizerEmployeeId','name employeeNo employeeCode').populate('createdBy','name')}
function normalized(body,settings){const start=safeDate(body.startAt);let end=safeDate(body.endAt);if(start&&!end)end=new Date(start.getTime()+Number(settings.defaultDurationHours||2)*3600000);return {title:String(body.title||'').trim(),category:body.category||'other',description:String(body.description||'').trim(),venue:String(body.venue||'').trim(),startAt:start,endAt:end,audienceType:body.audienceType||'all',branchId:body.branchId||null,academicSessionId:body.academicSessionId||null,targetProgramIds:cleanIds(body.targetProgramIds),targetSectionIds:cleanIds(body.targetSectionIds),employeeCategory:body.audienceType==='employee_category'?(body.employeeCategory||undefined):undefined,organizerEmployeeId:body.organizerEmployeeId||null,priority:body.priority||'normal',status:body.status||'draft',registrationRequired:Boolean(body.registrationRequired),capacity:Number(body.capacity||0)}}
function validatePayload(p,settings){if(!p.title)return 'Event Title is required';if(!p.startAt)return 'Start Date/Time is required';if(!p.endAt)return 'End Date/Time is required';if(p.endAt<p.startAt)return 'End Date/Time cannot be before Start Date/Time';if(p.audienceType==='program'&&!p.targetProgramIds.length)return 'Select at least one Program / Class';if(p.audienceType==='section'&&!p.targetSectionIds.length)return 'Select at least one Section';if(p.audienceType==='employee_category'&&!p.employeeCategory)return 'Select Employee Category';if(p.status==='scheduled'&&!settings.allowScheduledEvents)return 'Scheduled events are disabled in Event Settings';return ''}
async function visibleToUser(req,events){if(has(req.user,'MANAGE_EVENTS'))return events;let student=null,employee=null;if(req.user?.linkedStudentId)student=await Student.findOne({_id:req.user.linkedStudentId,collegeId:cid(req)}).lean();if(req.user?.linkedEmployeeId)employee=await Employee.findOne({_id:req.user.linkedEmployeeId,collegeId:cid(req)}).lean();return events.filter(e=>{const a=e.audienceType||'all';if(a==='all')return true;if(student){if(a==='students')return true;if(e.academicSessionId&&String(e.academicSessionId?._id||e.academicSessionId)!==String(student.academicSessionId||''))return false;if(a==='program')return (e.targetProgramIds||[]).some(x=>String(x._id||x)===String(student.programId||''));if(a==='section')return (e.targetSectionIds||[]).some(x=>String(x._id||x)===String(student.sectionId||''));return false}if(employee){if(a==='employees')return !e.branchId||String(e.branchId?._id||e.branchId)===String(employee.branchId||'');if(a==='employee_category')return (!e.branchId||String(e.branchId?._id||e.branchId)===String(employee.branchId||''))&&e.employeeCategory===employee.category;return false}return false})}

async function meta(req,res){const collegeId=cid(req);const [sessions,programs,sections,branches,employees,settings]=await Promise.all([AcademicSession.find({collegeId}).sort({startDate:-1}),Program.find({collegeId,isActive:true}).sort({name:1}),Section.find({collegeId}).sort({name:1}),Branch.find({collegeId,isActive:true}).sort({name:1}),Employee.find({collegeId,isActive:true}).select('name employeeNo employeeCode category branchId').sort({name:1}),getSettings(collegeId)]);res.json({sessions,programs,sections,branches,employees,settings})}
async function dashboard(req,res){const collegeId=cid(req);await refreshStatuses(collegeId);const now=new Date(),todayStart=new Date(now);todayStart.setHours(0,0,0,0);const todayEnd=new Date(now);todayEnd.setHours(23,59,59,999);const [total,upcoming,today,completed,cancelled,next]=await Promise.all([Event.countDocuments({collegeId}),Event.countDocuments({collegeId,status:'scheduled',startAt:{$gt:now}}),Event.countDocuments({collegeId,startAt:{$lte:todayEnd},endAt:{$gte:todayStart},status:{$nin:['draft','cancelled']}}),Event.countDocuments({collegeId,status:'completed'}),Event.countDocuments({collegeId,status:'cancelled'}),populate(Event.find({collegeId,status:{$in:['scheduled','active','published']},endAt:{$gte:now}}).sort({startAt:1}).limit(8))]);res.json({total,upcoming,today,completed,cancelled,next})}
async function listEvents(req,res){const collegeId=cid(req);await refreshStatuses(collegeId);const manager=has(req.user,'MANAGE_EVENTS');const q={collegeId};if(manager){if(req.query.status)q.status=req.query.status}else q.status={$in:['scheduled','active','published']};if(req.query.category)q.category=req.query.category;if(req.query.audienceType)q.audienceType=req.query.audienceType;if(req.query.from||req.query.to){q.startAt={};if(req.query.from)q.startAt.$gte=new Date(req.query.from);if(req.query.to){const d=new Date(req.query.to);d.setHours(23,59,59,999);q.startAt.$lte=d}}let docs=await populate(Event.find(q).sort({startAt:1}));docs=await visibleToUser(req,docs);res.json(docs)}
async function createEvent(req,res){const collegeId=cid(req),settings=await getSettings(collegeId);if(!settings.enabled)return bad(res,'Events module is disabled',403);const payload=normalized(req.body,settings),err=validatePayload(payload,settings);if(err)return bad(res,err);const doc=await Event.create({...payload,collegeId,eventNo:await nextEventNo(collegeId),createdBy:req.user._id});await audit(req,'CREATE_EVENT','Event',doc._id);res.status(201).json(doc)}
async function updateEvent(req,res){const collegeId=cid(req),settings=await getSettings(collegeId);const existing=await Event.findOne({_id:req.params.id,collegeId});if(!existing)return bad(res,'Event not found',404);if(['completed','cancelled'].includes(existing.status))return bad(res,'Completed/cancelled events cannot be edited',409);const payload=normalized(req.body,settings),err=validatePayload(payload,settings);if(err)return bad(res,err);Object.assign(existing,payload);await existing.save();await audit(req,'UPDATE_EVENT','Event',existing._id);res.json(existing)}
async function publishEvent(req,res){const collegeId=cid(req),settings=await getSettings(collegeId),doc=await Event.findOne({_id:req.params.id,collegeId});if(!doc)return bad(res,'Event not found',404);if(doc.status==='cancelled'||doc.status==='completed')return bad(res,'Cancelled/completed event cannot be published',409);const now=new Date();doc.status=doc.startAt>now?'scheduled':(doc.endAt>=now?'active':'completed');doc.publishedAt=now;await doc.save();await audit(req,'PUBLISH_EVENT','Event',doc._id,{status:doc.status,approvalRequired:settings.requireApprovalBeforePublishing});
  let uq={collegeId,isActive:true};
  if(doc.audienceType==='students'||doc.audienceType==='program'||doc.audienceType==='section'){
    const sq={collegeId,status:'active'};if(doc.academicSessionId)sq.academicSessionId=doc.academicSessionId;if(doc.audienceType==='program')sq.programId={$in:doc.targetProgramIds};if(doc.audienceType==='section')sq.sectionId={$in:doc.targetSectionIds};
    const ids=await Student.find(sq).distinct('_id');uq.linkedStudentId={$in:ids};
  }else if(doc.audienceType==='employees'||doc.audienceType==='employee_category'){
    const eq={collegeId,isActive:true};if(doc.branchId)eq.branchId=doc.branchId;if(doc.audienceType==='employee_category')eq.category=doc.employeeCategory;
    const ids=await Employee.find(eq).distinct('_id');uq.linkedEmployeeId={$in:ids};
  }
  pushNotifications.sendToUsers(collegeId,uq,{title:'New Event',body:doc.title,data:{type:'event',eventId:String(doc._id)}}).catch(err=>console.error('event_push_error',err.message));
  res.json(doc)}
async function cancelEvent(req,res){const doc=await Event.findOne({_id:req.params.id,collegeId:cid(req)});if(!doc)return bad(res,'Event not found',404);if(doc.status==='completed')return bad(res,'Completed event cannot be cancelled',409);doc.status='cancelled';doc.cancelledAt=new Date();await doc.save();await audit(req,'CANCEL_EVENT','Event',doc._id);res.json(doc)}
async function uploadAttachment(req,res){const settings=await getSettings(cid(req));if(!settings.allowAttachments)return bad(res,'Event attachments are disabled',403);if(!req.file)return bad(res,'Attachment is required');const doc=await Event.findOne({_id:req.params.id,collegeId:cid(req)});if(!doc)return bad(res,'Event not found',404);doc.attachmentUrl=`/uploads/events/${req.file.filename}`;doc.attachmentName=req.file.originalname||req.file.filename;await doc.save();await audit(req,'UPLOAD_EVENT_ATTACHMENT','Event',doc._id);res.json(doc)}
async function settings(req,res){res.json(await getSettings(cid(req)))}
async function saveSettings(req,res){const allowed=['enabled','allowAttachments','allowScheduledEvents','defaultDurationHours','requireApprovalBeforePublishing','showEventsOnDashboard'];const set={};for(const k of allowed)if(req.body[k]!==undefined)set[k]=req.body[k];const doc=await EventSettings.findOneAndUpdate({collegeId:cid(req)},{$set:set,$setOnInsert:{collegeId:cid(req)}},{new:true,upsert:true,runValidators:true,setDefaultsOnInsert:true});await audit(req,'UPDATE_EVENT_SETTINGS','EventSettings',doc._id);res.json(doc)}

async function register(req,res){const collegeId=cid(req);await refreshStatuses(collegeId);const event=await Event.findOne({_id:req.params.id,collegeId,status:{$in:['scheduled','active','published']}});if(!event)return bad(res,'Event not found',404);if(!event.registrationRequired)return bad(res,'Registration is not required for this event');const participant=ownParticipant(req.user);if(!participant)return bad(res,'Only linked student/employee accounts can self-register',403);if(event.capacity>0){const count=await EventRegistration.countDocuments({collegeId,eventId:event._id,status:'registered'});if(count>=event.capacity)return bad(res,'Event capacity reached')}try{const doc=await EventRegistration.create({collegeId,eventId:event._id,...participant,status:'registered'});await audit(req,'REGISTER_EVENT','EventRegistration',doc._id,{eventId:event._id});res.status(201).json(doc)}catch(e){if(e?.code===11000)return bad(res,'Already registered for this event',409);throw e}}
async function listRegistrations(req,res){const q={collegeId:cid(req)};if(req.query.eventId)q.eventId=req.query.eventId;if(!has(req.user,'VIEW_EVENT_REPORTS')){const own=ownParticipant(req.user);if(own)Object.assign(q,own)}res.json(await EventRegistration.find(q).populate('eventId','eventNo title startAt venue').populate('studentId','name admissionNo rollNo').populate('employeeId','name employeeNo employeeCode').sort({registeredAt:-1}))}
async function markAttendance(req,res){const doc=await EventRegistration.findOne({_id:req.params.registrationId,collegeId:cid(req)});if(!doc)return bad(res,'Registration not found',404);doc.status=req.body.status||'attended';if(doc.status==='attended')doc.checkedInAt=new Date();await doc.save();await audit(req,'UPDATE_EVENT_ATTENDANCE','EventRegistration',doc._id,{status:doc.status});res.json(doc)}

module.exports={meta,dashboard,listEvents,createEvent,updateEvent,publishEvent,cancelEvent,uploadAttachment,settings,saveSettings,register,listRegistrations,markAttendance};
