const P = {
  // College / Users / Roles
  MANAGE_COLLEGE: 'MANAGE_COLLEGE',
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_USER_ROLES: 'MANAGE_USER_ROLES',
  MANAGE_ROLES: 'MANAGE_ROLES',

  // Admissions
  VIEW_ADMISSIONS: 'VIEW_ADMISSIONS',
  MANAGE_ADMISSIONS: 'MANAGE_ADMISSIONS',
  APPROVE_ADMISSIONS: 'APPROVE_ADMISSIONS',
  MANAGE_STUDENT_LIFECYCLE: 'MANAGE_STUDENT_LIFECYCLE',

  // Students / Employees
  VIEW_STUDENTS: 'VIEW_STUDENTS',
  MANAGE_STUDENTS: 'MANAGE_STUDENTS',
  VIEW_EMPLOYEES: 'VIEW_EMPLOYEES',
  MANAGE_EMPLOYEES: 'MANAGE_EMPLOYEES',

  // Academics
  VIEW_ACADEMICS: 'VIEW_ACADEMICS',
  MANAGE_ACADEMICS: 'MANAGE_ACADEMICS',

  // Attendance
  VIEW_ATTENDANCE: 'VIEW_ATTENDANCE',
  MARK_ATTENDANCE: 'MARK_ATTENDANCE',
  CORRECT_ATTENDANCE: 'CORRECT_ATTENDANCE',

  // Biometric
  MANAGE_BIOMETRIC: 'MANAGE_BIOMETRIC',

  // Fees / Finance
  VIEW_FEES: 'VIEW_FEES',
  MANAGE_FEES: 'MANAGE_FEES',

  // Existing payment permissions
  RECEIVE_FEE_PAYMENTS: 'RECEIVE_FEE_PAYMENTS',
  VOID_FEE_PAYMENTS: 'VOID_FEE_PAYMENTS',

  // New fee workflow permissions
  POST_FEE_PAYMENTS: 'POST_FEE_PAYMENTS',
  LOCK_FEE_PACKAGE: 'LOCK_FEE_PACKAGE',
  VIEW_FEE_AUDIT: 'VIEW_FEE_AUDIT',

  // Finance
  VIEW_FINANCE: 'VIEW_FINANCE',
  MANAGE_FINANCE: 'MANAGE_FINANCE',
  CREATE_FINANCE_TRANSACTION: 'CREATE_FINANCE_TRANSACTION',
  APPROVE_FINANCE_TRANSACTION: 'APPROVE_FINANCE_TRANSACTION',
  POST_FINANCE_TRANSACTION: 'POST_FINANCE_TRANSACTION',
  REVERSE_FINANCE_TRANSACTION: 'REVERSE_FINANCE_TRANSACTION',
  MANAGE_FINANCE_ACCOUNTS: 'MANAGE_FINANCE_ACCOUNTS',
  MANAGE_FINANCE_HEADS: 'MANAGE_FINANCE_HEADS',
  VIEW_FINANCE_REPORTS: 'VIEW_FINANCE_REPORTS',
  MANAGE_EXPENSES: 'MANAGE_EXPENSES',

  // Exams / Results
  VIEW_EXAMS: 'VIEW_EXAMS',
  MANAGE_EXAMS: 'MANAGE_EXAMS',
  ENTER_EXAM_MARKS: 'ENTER_EXAM_MARKS',
  VERIFY_EXAM_MARKS: 'VERIFY_EXAM_MARKS',
  PUBLISH_RESULTS: 'PUBLISH_RESULTS',
  MANAGE_GRADING: 'MANAGE_GRADING',
  VIEW_RESULT_REPORTS: 'VIEW_RESULT_REPORTS',

  // Library
  VIEW_LIBRARY: 'VIEW_LIBRARY',
  MANAGE_LIBRARY: 'MANAGE_LIBRARY',
  ISSUE_LIBRARY_BOOKS: 'ISSUE_LIBRARY_BOOKS',
  RETURN_LIBRARY_BOOKS: 'RETURN_LIBRARY_BOOKS',
  MANAGE_LIBRARY_FINES: 'MANAGE_LIBRARY_FINES',
  MANAGE_LIBRARY_SETTINGS: 'MANAGE_LIBRARY_SETTINGS',
  VIEW_LIBRARY_REPORTS: 'VIEW_LIBRARY_REPORTS',

  // Transport
  VIEW_TRANSPORT: 'VIEW_TRANSPORT',
  MANAGE_TRANSPORT: 'MANAGE_TRANSPORT',
  MANAGE_TRANSPORT_VEHICLES: 'MANAGE_TRANSPORT_VEHICLES',
  MANAGE_TRANSPORT_ROUTES: 'MANAGE_TRANSPORT_ROUTES',
  MANAGE_TRANSPORT_ASSIGNMENTS: 'MANAGE_TRANSPORT_ASSIGNMENTS',
  MANAGE_TRANSPORT_MAINTENANCE: 'MANAGE_TRANSPORT_MAINTENANCE',
  VIEW_TRANSPORT_REPORTS: 'VIEW_TRANSPORT_REPORTS',

  // Hostel
  VIEW_HOSTEL: 'VIEW_HOSTEL',
  MANAGE_HOSTEL: 'MANAGE_HOSTEL',
  MANAGE_HOSTELS: 'MANAGE_HOSTELS',
  MANAGE_HOSTEL_ROOMS: 'MANAGE_HOSTEL_ROOMS',
  MANAGE_HOSTEL_ALLOCATIONS: 'MANAGE_HOSTEL_ALLOCATIONS',
  MANAGE_HOSTEL_MESS: 'MANAGE_HOSTEL_MESS',
  MANAGE_HOSTEL_COMPLAINTS: 'MANAGE_HOSTEL_COMPLAINTS',
  VIEW_HOSTEL_REPORTS: 'VIEW_HOSTEL_REPORTS',

  // Payroll / HR
  VIEW_PAYROLL: 'VIEW_PAYROLL',
  MANAGE_PAYROLL: 'MANAGE_PAYROLL',
  MANAGE_EMPLOYEE_CONTRACTS: 'MANAGE_EMPLOYEE_CONTRACTS',
  MANAGE_SALARY_STRUCTURES: 'MANAGE_SALARY_STRUCTURES',
  MANAGE_EMPLOYEE_LEAVE: 'MANAGE_EMPLOYEE_LEAVE',
  APPROVE_EMPLOYEE_LEAVE: 'APPROVE_EMPLOYEE_LEAVE',
  MANAGE_EMPLOYEE_LOANS: 'MANAGE_EMPLOYEE_LOANS',
  GENERATE_PAYROLL: 'GENERATE_PAYROLL',
  APPROVE_PAYROLL: 'APPROVE_PAYROLL',
  MARK_PAYROLL_PAID: 'MARK_PAYROLL_PAID',
  VIEW_PAYROLL_REPORTS: 'VIEW_PAYROLL_REPORTS',

  // Notices / Communication
  VIEW_NOTICES: 'VIEW_NOTICES',
  MANAGE_NOTICES: 'MANAGE_NOTICES',
  SEND_NOTICES: 'SEND_NOTICES',
  VIEW_COMMUNICATION_REPORTS: 'VIEW_COMMUNICATION_REPORTS',

  // Reports
  VIEW_REPORTS: 'VIEW_REPORTS',

  // Events
  MANAGE_EVENTS: 'MANAGE_EVENTS',
  VIEW_EVENTS: 'VIEW_EVENTS',
  MANAGE_EVENT_REGISTRATIONS: 'MANAGE_EVENT_REGISTRATIONS',
  VIEW_EVENT_REPORTS: 'VIEW_EVENT_REPORTS'
};

module.exports = Object.freeze(P);